import {cameraExercise} from './camera-exercise.js';
import {Diagnostics} from './diagnostics.js';
import {describeCell} from './describe-cell.js';
import {SCENARIOS} from './scenarios.js';
import {MapView,LAYERS} from './map.js';import {SPECIES} from './species.js';
const $=s=>document.querySelector(s),fmt=(v,d=1)=>Number.isFinite(v)?v.toLocaleString('zh-CN',{maximumFractionDigits:d}):'—';let worker,state,tab='detail',selection=0,toastTimer;
const diagnostics=new Diagnostics();function post(cmd){if(!worker)return;cmd.requestId=diagnostics.request(cmd.type);worker.postMessage(cmd);}
const map=new MapView($('#map'),i=>{selection=i;$('#inspector').hidden=false;post({type:'select',i});});
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4000);}
const escape=s=>String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function row(label,value){return `<div class="row"><span>${label}</span><strong>${value}</strong></div>`;}
function startWorker(){worker?.terminate();worker=new Worker('/src/worker.js',{type:'module'});worker.onerror=e=>{toast('模拟异常：'+e.message);$('#loading').hidden=true;};worker.onmessage=({data:d})=>{if(d.type==='state'){if(!d.regions)d.regions=state?.regions;state=d;$('#loading').hidden=true;map.update(d);$('#time').textContent=`第 ${fmt(d.year,2)} 年`;$('#play').textContent=d.running?'Ⅱ 暂停':'▶ 运行';$('#state').textContent=`${d.running?'运行':'暂停'} · ${d.size}²${d.targetYear!=null?' → '+fmt(d.targetYear,2)+' 年':''}`;for(const id of ['play','step','save','advanceOpen'])$('#'+id).disabled=false;$('#stats').textContent=`草 ${fmt(d.summary.plants,0)} · 树 ${fmt(d.summary.trees,0)} · 古树 ${d.summary.ancients} · 账差 ${d.audit.error.toExponential(1)}`;$('#eventCount').textContent=d.events.length;$('#eventRetention').textContent=d.dropped?`列表仅显示最近 60 条 · 更早 ${d.dropped} 条已截断`:'列表仅显示最近 60 条 · 存档最多保留 2000 条';renderDetail(d.selected);renderEvents();flowLegend();regionLegend();diagnostics.reply(d.replyTo);window.ecologyState=d;}
 else if(d.type==='progress'){$('#loading').hidden=false;$('#loadingText').textContent=d.text;}
 else if(d.type==='error'){toast(d.text);if(d.action==='edit')$('#editError').textContent=d.text;$('#loading').hidden=true;}
 else if(d.type==='notice')toast(d.text);
 else if(d.type==='save'){diagnostics.reply(d.replyTo);const blob=new Blob([JSON.stringify(d.data)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`青野-${state.seed}-${state.year}年.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('存档已导出');}};}
function generate(){const size=Number($('#size').value),climate=Number($('#climate').value),rain=Number($('#rain').value),climateGradient=Number($('#climateGradient').value),geothermal=Number($('#geothermal').value);if(!Number.isFinite(climateGradient)||climateGradient<0||climateGradient>80||!Number.isFinite(climate)||climate< -20||climate>50||rain<0||rain>1||geothermal<0||geothermal>3){toast('请检查生成参数范围');return;}startWorker();map.state=null;map.fitted=false;$('#inspector').hidden=true;$('#loading').hidden=false;$('#loadingText').textContent='正在生成…';post({type:'generate',size,seed:$('#seed').value||'青野',prewarm:Number($('#startMode').value),scenario:$('#scenario').value,variant:$('#variant').value,config:{climate,climateGradient,rain,geothermal}});}
function renderDetail(d){const summary=describeCell(d);$('#cellTitle').textContent=`格 ${d.x}, ${d.y}`;$('#detail').innerHTML=regionSummary(d)+`<details class="cell-drilldown"><summary>检查此格 · ${d.x}, ${d.y}</summary><section class="cell-summary"><div class="summary-time">第 ${fmt(d.year,2)} 年 · 格 ${d.x}, ${d.y}</div><strong class="summary-title">${summary.thermal}${summary.terrain}</strong><div class="summary-ecosystem">${summary.moisture} · ${summary.ecosystem}</div><div class="summary-features">${summary.features.map((f,i)=>`<span title="${escape(summary.reasons[i])}">${f}</span>`).join('')}</div><div class="summary-bands"><span title="固定分级：${summary.gradeRange}；只描述地表游离量">地表 ${summary.grade} 级 · ${summary.gradeName}</span><span>${summary.plantStage===null?'无灵植':`灵植 ${summary.plantStage} 阶`}</span></div><p>${summary.change}</p><small>${summary.storage}。地表等级不代表地下储量或植物境界。</small></section><h3>地理与小环境</h3>`+row('海拔指数',fmt(d.height,3))+row('岩性 / 地热',`${fmt(d.rock,2)} / +${fmt(d.heat)} °C`)+row('背景 → 实际气温',`${fmt(d.baseTemp)} → ${fmt(d.temp)} °C`)+row('背景 → 实际水分',`${fmt(d.baseWater,2)} → ${fmt(d.water,2)}`)+row('日照',fmt(d.sun,2))+'<h3>灵气 · 单位 / 格</h3>'+row('地下聚气效率',fmt(d.groundGatherRate,3))+row('地表聚气效率 / 上限',fmt(d.gatherRate,3)+' / '+fmt(d.gatherLimit))+row('地下 / 容量',`${fmt(d.ground)} / ${fmt(d.capacity)}`)+row('地表 / 矿物结合',`${fmt(d.air)} / ${fmt(d.mineral)}`)+row('土壤结合 / 遗留物',`${fmt(d.soil)} / ${fmt(d.detritus)}`)+row('加工吞吐 / 年',fmt(d.production))+row('天道接收 / 年',fmt(d.receive))+row('地质转化比例',fmt(d.efficiency,2))+row('传导 / 释放系数',`${fmt(d.conduct,3)} / ${fmt(d.outlet,3)}`)+row('地表 / 岩土容量',fmt(d.airCapacity)+' / '+fmt(d.soilCapacity))+row('岩土结合 / 释放速率',fmt(d.soilBindRate,3)+' / '+fmt(d.soilReleaseRate,3))+row('地表通达 北 / 南',fmt(d.surfaceNorth,3)+' / '+fmt(d.surfaceSouth,3))+row('地表通达 西 / 东',fmt(d.surfaceWest,3)+' / '+fmt(d.surfaceEast,3))+'<h3>植物种群</h3>'+d.plants.map((p,l)=>p.count?`<div class="plant"><div class="plant-title"><span>${SPECIES[p.type].name}</span><span>${fmt(p.count,0)} 株</span></div>${row('积累阶段',p.stage?`质变 ${p.stage} 阶`:'初生结构')}${row('生物量 / 后天积累',`${fmt(p.mass)} / ${fmt(p.qi)}`)}${row('平均年龄 / 先天余量',`${fmt(p.age)} 年 / ${fmt(p.life)}`)}${row('加工 / 地下吸收',`${fmt(p.traits.process,2)} / ${fmt(p.traits.root,2)}`)}${row('地表吸收 / 释放',`${fmt(p.traits.absorb,2)} / ${fmt(p.traits.release,2)}`)}${p.ancient?`<div class="ancient">古树 1 株 · ${fmt(p.ancient.age)} 年 · 后天 ${fmt(p.ancient.qi)}</div>`:''}</div>`:`<div class="plant muted">${l?'树':'草'}层暂无植物</div>`).join('')+'<h3>当地种源</h3>'+ (d.seeds.length?d.seeds.map(s=>row(s.name,`${fmt(s.count)} · ${fmt(s.age)} 年`)).join(''):'<p class="muted">没有存留种子；恢复需邻格种源。</p>')+'</details>';
 const labels={geology:'天道 → 地下',processing:'天道 → 植物',groundIn:'地下邻格流入',groundOut:'地下邻格流出',surfaceIn:'地表邻格流入',surfaceOut:'地表邻格流出',vent:'地下 → 地表',absorb:'地表 → 植物',root:'地下 → 植物',release:'植物 → 地表',decompose:'遗留物 → 地表',bind:'游离 → 结合',weather:'土壤 → 地表',litter:'植物 → 凋落物',death:'死亡 → 遗骸',escape:'地表 → 宇宙逸散',edit:'人工净增减'};$('#ledger').innerHTML=`<h3>${d.ledgerSpan===0?'本次人工编辑':'最近一步 · '+fmt(state.config.dt,2)+' 年'}</h3><p class="muted">各项是转移量；内部转移不能再计入净输入。</p>`+Object.entries(labels).map(([k,v])=>row(v,fmt(d.flows[k],4))).join('')+(d.ledgerSpan===0?'':d.plants.filter(p=>p.count).map(p=>'<h3>'+SPECIES[p.type].name+' · 本步取用</h3>'+row('天道加工 / 地下吸收',fmt(p.flows.processing,4)+' / '+fmt(p.flows.root,4))+row('地表吸收 / 向外释放',fmt(p.flows.absorb,4)+' / '+fmt(p.flows.release,4))).join(''))+'<h3>相邻边实际流向</h3>'+row('地下 东边 / 南边',fmt(d.groundEast,4)+' / '+fmt(d.groundSouth,4))+row('地表 东边 / 南边',fmt(d.airEast,4)+' / '+fmt(d.airSouth,4))+'<p class="muted">正数朝东／南，负数朝西／北；单位为最近一步每条边的转移量。初始与旧档未记录时，单步后可查看。</p><h3>本格总量</h3>'+row('期初 → 期末',`${fmt(d.before,4)} → ${fmt(d.after,4)}`)+row('净变化',fmt(d.after-d.before,4))+`<p class="muted">地图侧边封闭，州界不影响流动；地表游离灵气持续逸散到宇宙。以上只解释最近一步，不代替完整历史。</p><h3>本格近期事件</h3><p class="muted">仅显示留存记录中本格最近 20 条。未记录或已截断的历史原因未知；有事件也不代表历史完整。自然事件时间标记所在步的起点，步长 ${fmt(state.config.dt,2)} 年；人工操作标记提交边界。</p>`+(d.events.map(e=>`<p class="muted">${fmt(e.year,2)} 年 · ${escape(e.type)}${e.cause?' · '+escape(e.cause):''}</p><details><summary>事件依据</summary><pre class="event-facts">${escape(JSON.stringify(e,null,2))}</pre></details>`).join('')||'<p class="muted">近期没有记录；更早原因不作推测。</p>');preview();}
function renderEvents(){if(!state)return;$('#events').innerHTML=state.events.slice().reverse().map(e=>`<button data-cell="${e.i}">${fmt(e.year,2)} 年 · ${e.i%state.size}, ${Math.floor(e.i/state.size)} · ${escape(e.type)}${e.species!==undefined?' · '+SPECIES[e.species].name:''}</button>`).join('')||'<p class="muted">暂无关键事件。</p>';$('#events').querySelectorAll('button').forEach(b=>b.onclick=()=>{selection=Number(b.dataset.cell);map.selected=selection;map.dirty=true;$('#inspector').hidden=false;post({type:'select',i:selection});});}
for(const [id,name,color]of LAYERS){const b=document.createElement('button');b.dataset.layer=id;b.innerHTML=`<span class="swatch" style="background:${color}"></span>${name}`;if(id==='natural')b.classList.add('active');b.onclick=()=>{$('#layerButtons .active')?.classList.remove('active');b.classList.add('active');map.setLayer(id);const l=LAYERS.find(l=>l[0]===id);$('#legendLabel').textContent=name;$('#range').textContent=id==='natural'?'格网尺度未换算公里':id==='flow'?'金：地下 · 青：地表｜最近一步流线｜线宽固定 0—10':`${l[3]}—${l[4]} · ${l[5]}`;$('#ramp').hidden=['natural','flow'].includes(id);flowLegend();};$('#layerButtons').append(b);}$('#ramp').hidden=true;$('#range').textContent='格网尺度未换算公里';
$('#generateOpen').onclick=()=>$('#generation').showModal();$('#generate').onclick=e=>{e.preventDefault();$('#generation').close();generate();};$('#play').onclick=()=>post({type:state?.running?'pause':'play'});$('#step').onclick=()=>post({type:'step'});$('#speed').onchange=()=>post({type:'speed',value:Number($('#speed').value)});$('#fit').onclick=()=>map.fit();$('#zoomIn').onclick=()=>map.scale(1.4);$('#zoomOut').onclick=()=>map.scale(1/1.4);$('#borders').onchange=e=>{map.borders=e.target.checked;map.dirty=true;};$('#collapseLayers').onclick=()=>{$('#layers').hidden=true;$('#showLayers').hidden=false;};$('#showLayers').onclick=()=>{$('#layers').hidden=false;$('#showLayers').hidden=true;};$('#closeInspector').onclick=()=>$('#inspector').hidden=true;$('.tabs').onclick=e=>{if(!e.target.dataset.tab)return;tab=e.target.dataset.tab;for(const t of ['detail','ledger','edit'])$('#'+t).hidden=t!==tab;document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));};$('#help').onclick=()=>$('#helpDialog').showModal();$('#helpClose').onclick=()=>$('#helpDialog').close();$('#eventsToggle').onclick=()=>$('#eventsPanel').hidden=!$('#eventsPanel').hidden;$('#eventsClose').onclick=()=>$('#eventsPanel').hidden=true;
$('#save').onclick=()=>post({type:'save'});$('#load').onclick=()=>$('#file').click();$('#file').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;const data=JSON.parse(await f.text());if(!worker)startWorker();post({type:'load',data});}catch{toast('文件无法读取，当前世界未改变');}e.target.value='';};$('#cancel').onclick=()=>{worker?.terminate();worker=null;$('#loading').hidden=true;$('#state').textContent='已取消';for(const id of ['play','step','save','advanceOpen'])$('#'+id).disabled=true;};
const fields={groundGatherRate:'地下聚气效率',gatherRate:'地理聚气效率',gatherLimit:'地理聚气上限',ground:'地下库存',air:'地表库存',airCapacity:'地表容纳上限',soilCapacity:'岩土结合容量',soilBindRate:'岩土结合速率',soilReleaseRate:'岩土释放速率',heat:'地热增温',baseTemp:'背景气温',baseWater:'背景水分',conduct:'地下通道系数',outlet:'地下释放系数',surfaceNorth:'地表北向通达',surfaceSouth:'地表南向通达',surfaceWest:'地表西向通达',surfaceEast:'地表东向通达'},traits={process:'天道加工',absorb:'地表吸收',root:'地下吸收',release:'释放系数',capacity:'承载能力'};
SPECIES.forEach((s,i)=>$('#editSpecies').add(new Option(s.name,i)));
function editFields(){const kind=$('#editKind').value;$('#fieldRow').hidden=!['field','trait'].includes(kind);$('#plantRow').hidden=kind!=='plant';$('#ancientRow').hidden=kind!=='plant';$('#layerRow').hidden=!['trait','death','remove'].includes(kind);$('#valueRow').hidden=['death','remove'].includes(kind);$('#editField').innerHTML='';for(const[k,v]of Object.entries(kind==='trait'?traits:fields))$('#editField').add(new Option(v,k));$('#editError').textContent='';preview();}
function preview(){if(!state)return;const d=state.selected,kind=$('#editKind').value,field=$('#editField').value;let before=kind==='field'?d[field]:kind==='trait'?d.plants[Number($('#editLayer').value)]?.traits?.[field]:null;$('#editPreview').textContent=`格 ${d.x}, ${d.y} · ${before!=null?'当前 '+fmt(before,3)+' → '+$('#editValue').value:kind==='death'?'死亡后保留后天遗骸':kind==='remove'?'移除量记为外部输出':'添加 '+$('#editValue').value+' 株'}`;}
$('#editKind').onchange=editFields;for(const id of ['editField','editValue','editLayer'])$('#'+id).oninput=preview;editFields();$('#applyEdit').onclick=()=>{if(!state)return;$('#editError').textContent='';post({type:'edit',cmd:{i:state.selected.i,kind:$('#editKind').value,field:$('#editField').value,value:Number($('#editValue').value),species:Number($('#editSpecies').value),layer:Number($('#editLayer').value),ancient:$('#editAncient').checked}});};
document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)||document.querySelector('dialog[open]'))return;if(e.code==='Space'){e.preventDefault();post({type:state?.running?'pause':'play'});}if(e.key.toLowerCase()==='f')map.fit();if(e.key==='Escape'){$('#inspector').hidden=true;$('#eventsPanel').hidden=true;}});
for(const[id,name]of SCENARIOS)$('#scenario').add(new Option(`${id} · ${name}`,id));$('#scenario').onchange=()=>{const chosen=!!$('#scenario').value;$('#variantRow').hidden=!chosen;$('#scenarioNote').hidden=!chosen;for(const id of ['seed','size','climate','climateGradient','rain','geothermal'])$('#'+id).disabled=chosen;};
window.ecology={map,generate,get state(){return state;},select(i){selection=i;map.selected=i;$('#inspector').hidden=false;post({type:'select',i});},command(d){post(d);}};
generate();

map.onFrame=(time,drew)=>diagnostics.frame(time,drew);$('#diagnosticsStart').onclick=()=>{exerciseReport=null;diagnostics.begin();$('#helpDialog').close();toast('开始记录交互性能');};$('#diagnosticsReport').onclick=()=>{$('#diagnosticsOutput').textContent=JSON.stringify(diagnostics.report(state),null,2);};

$('#advanceOpen').onclick=()=>{$('#advanceFrom').textContent='当前第 '+fmt(state.year,2)+' 年';$('#advanceDialog').showModal();};$('#advanceRun').onclick=e=>{e.preventDefault();const input=$('#advanceYears');if(!input.reportValidity())return;$('#advanceDialog').close();$('#speed').value='64';post({type:'advance',years:Number(input.value)});};

function flowLegend(){if(map.layer!=='flow')return;$('#range').textContent=state?.edgeFlowStep?'实际流线：金地下／青地表 · 线宽 0—10 单位/步 · 光晕仅示库存高值｜第 '+state.edgeFlowStep+' 步':'尚无实际流量记录；单步后追踪路线';}

let cameraCancel=null,exerciseReport=null;
$('#cameraExercise').onclick=()=>{if(!state)return;cameraCancel?.();$('#helpDialog').close();$('#speed').value='4';post({type:'speed',value:4});if(!state.running)post({type:'play'});exerciseReport=null;cameraCancel=cameraExercise(map,diagnostics,()=>{exerciseReport={workload:'60 s automated camera motion through normal renderer with simulation running',...diagnostics.report(state)};post({type:'pause'});$('#diagnosticsOutput').textContent=JSON.stringify(exerciseReport,null,2);cameraCancel=null;toast('60 秒平移缩放测试完成');});toast('正在测试，60 秒后自动暂停并恢复视角');};
$('#diagnosticsReport').onclick=()=>{$('#diagnosticsOutput').textContent=JSON.stringify(exerciseReport||diagnostics.report(state),null,2);};

function regionSummary(d){const list=d.regions||[];return '<section class="region-summary"><h3>所在地域</h3><p class="muted">各维度可重叠 · 按模拟年更新 · 显著不代表适宜修炼</p>'+ (list.length?list.map(r=>'<article><strong>'+escape(r.label)+'</strong><small> #'+r.id+' · '+(r.status==='fading'?'持续减弱':r.formed===null?'形成时间未知':'第 '+fmt(r.formed)+' 年成区')+'</small>'+row('规模',fmt(r.area,0)+' 格')+row('平均温度 / 水分',fmt(r.temperature)+' °C / '+fmt(r.water,2))+(r.dimension==='ancient'?row('作用源',escape(r.sourceId||'未知')+' · 格 '+(r.sourceCell%state.size)+', '+Math.floor(r.sourceCell/state.size)):'')+(r.dimension==='qi'?row('生产 / 聚气 / 输送 · 年均',fmt(r.qiRates?.production||0)+' / '+fmt(r.qiRates?.gathering||0)+' / '+fmt(r.qiRates?.transport||0)):'')+(r.dimension==='forest'?row('树 / 灵树 / 古树',fmt(r.trees,0)+' / '+fmt(r.spiritTrees,0)+' / '+fmt(r.ancients,0)):'')+'</article>').join(''):'<p class="muted">此处尚无达到规模的已记录区域。</p>')+'<p class="muted">灵气片区需连续五年达到规模；聚气区不自动等于福地。古树分牵引与滋养：前者标出实际流动中由该树增强的通道，后者参与局部温湿度计算。</p></section>'; }
const regionOptions=[['significant','综合地域'],['landform','地形'],['thermal','温度'],['forest','林区'],['qi','灵气特点'],['ancient','古树作用']];
let selectedRegion='significant';
function regionLegend(){if(!state||map.regionMode==='off'||selectedRegion==='significant')return;const dimensions=selectedRegion==='thermal'?['thermal','geothermal']:[selectedRegion],count=(state.regions?.items||[]).filter(r=>r.status!=='candidate'&&dimensions.includes(r.dimension)).length;$('#range').textContent=!count?'当前尚无达到规模与持续时间要求的片区':selectedRegion==='qi'?'赭：生产 · 青：聚气 · 蓝：输送 · '+count+' 个片区':selectedRegion==='ancient'?'青蓝：牵引 · 草绿：滋养 · '+count+' 个片区':'色块表示片区 · 选中强调轮廓 · '+count+' 个片区';}
function showScale(regional){$('#layerButtons').hidden=regional;$('#regionButtons').hidden=!regional;for(const [id,active]of [['scaleCells',!regional],['scaleRegions',regional]]){$('#'+id).classList.toggle('active',active);$('#'+id).setAttribute('aria-pressed',String(active));}if(regional){$('#layerButtons [data-layer="natural"]').click();map.regionMode=selectedRegion;$('#legendLabel').textContent='片区 · '+regionOptions.find(r=>r[0]===selectedRegion)[1];$('#range').textContent=selectedRegion==='qi'?'赭：生产 · 青：聚气 · 蓝：输送 · 连续五年成区':selectedRegion==='ancient'?'青蓝：牵引 · 草绿：滋养 · 连续五年成区':'色块表示片区 · 选中强调轮廓 · 可展开格子数据';}else{map.regionMode='off';$('#layerButtons .active')?.click();}regionLegend();map.dirty=true;}
for(const [id,label]of regionOptions){const button=document.createElement('button');button.textContent=label;button.dataset.region=id;button.classList.toggle('active',id===selectedRegion);button.onclick=()=>{selectedRegion=id;$('#regionButtons .active')?.classList.remove('active');button.classList.add('active');showScale(true);};$('#regionButtons').append(button);}
$('#scaleCells').onclick=()=>showScale(false);$('#scaleRegions').onclick=()=>showScale(true);showScale(true);
