// Passive bounded measurements. Never advances the world or alters camera behavior.
export class Diagnostics{
 constructor(){this.start=performance.now();this.nextId=0;this.pending=new Map();this.samples={};this.frames=[];this.lastFrame=null;this.draws=0;this.recording=false;this.session=null;this.memorySamples=[];this.lastMemory=0;}
 request(type){const id=++this.nextId;if(['generate','select','edit','play','pause','step','load','save'].includes(type)){this.pending.set(id,{type,start:performance.now()});if(this.pending.size>100)this.pending.delete(this.pending.keys().next().value);}return id;}
 reply(id){const p=this.pending.get(id);if(!p)return;const list=this.samples[p.type]||=[];list.push(performance.now()-p.start);if(list.length>200)list.shift();this.pending.delete(id);}
 frame(time,drew){if(this.lastFrame!==null){this.frames.push(time-this.lastFrame);if(this.frames.length>3600)this.frames.shift();}this.lastFrame=time;if(drew)this.draws++;if(this.recording){this.session.frames++;this.session.draws+=drew?1:0;if(time-this.lastMemory>=10000){this.lastMemory=time;this.memorySamples.push({elapsedSeconds:(time-this.session.start)/1000,used:performance.memory?.usedJSHeapSize??null,total:performance.memory?.totalJSHeapSize??null});if(this.memorySamples.length>181)this.memorySamples.shift();}}}
 begin(){this.recording=true;this.session={start:performance.now(),frames:0,draws:0};this.samples={};this.frames=[];this.lastFrame=null;this.memorySamples=[];this.lastMemory=0;}
 report(state){const percentile=(a,p)=>a.length?[...a].sort((x,y)=>x-y)[Math.min(a.length-1,Math.floor(a.length*p))]:null,elapsed=this.session?(performance.now()-this.session.start)/1000:0;return{userAgent:navigator.userAgent,viewport:{width:innerWidth,height:innerHeight},size:state?.size,year:state?.year,steps:state?.steps,elapsedSeconds:elapsed,frames:this.session?.frames||0,draws:this.session?.draws||0,rafFps:elapsed?this.session.frames/elapsed:null,frameP95:percentile(this.frames,.95),requests:Object.fromEntries(Object.entries(this.samples).map(([k,v])=>[k,{count:v.length,p50:percentile(v,.5),p95:percentile(v,.95),max:Math.max(...v)}])),memoryTimeline:this.memorySamples.map(s=>({...s})),memory:performance.memory?{used:performance.memory.usedJSHeapSize,total:performance.memory.totalJSHeapSize}:null};}
}
