import {ancientMicroclimate,observeAncients} from './ancient-influence.js';
import {gatheringDefaults,transportQi,observeQi} from './qi-transport.js';
import {updateRegions,restoreRegions,regionsAt} from './regions.js';
import {partition} from './geography.js';
import {generateTerrain} from './terrain.js';
import {validateState} from './validate-state.js';
import {landformDetails} from './landforms.js';
import {SPECIES,DEFAULTS,VERSION} from './species.js';
export const FIELDS=['groundGatherRate','gatherRate','gatherLimit','sourceMean','throughputMean','gatherMean','airCapacity','soilCapacity','soilBindRate','soilReleaseRate','surfaceNorth','surfaceSouth','surfaceWest','surfaceEast','fracture','groundEast','groundSouth','airEast','airSouth','height','river','lakeDepth','lakeIsland','rock','heat','sun','baseTemp','baseWater','temp','water','province','receive','efficiency','production','capacity','conduct','outlet','ground','air','mineral','soil','detritus','mineralTime'];
export const FLOWS=['geology','processing','groundIn','groundOut','surfaceIn','surfaceOut','vent','absorb','root','release','decompose','bind','weather','litter','death','escape','edit'];
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
function hashSeed(s){let h=2166136261;for(const c of String(s))h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0||1;}
function hash(x,y,s){let h=Math.imul(x+374761393,668265263)^Math.imul(y+1274126177,1597334677)^s;h=Math.imul(h^(h>>>13),1274126177);return ((h^(h>>>16))>>>0)/4294967295;}
function noise(x,y,s){const ix=Math.floor(x),iy=Math.floor(y),fx=x-ix,fy=y-iy,u=fx*fx*(3-2*fx),v=fy*fy*(3-2*fy);return (hash(ix,iy,s)*(1-u)+hash(ix+1,iy,s)*u)*(1-v)+(hash(ix,iy+1,s)*(1-u)+hash(ix+1,iy+1,s)*u)*v;}
export class World{
 constructor(size=256,seed='青野-001',config={}){
  if(![16,32,64,128,256].includes(size))throw Error('地图尺寸不支持');
  this.initializing=true;this.version=VERSION;this.size=size;this.n=size*size;this.seed=String(seed);this.rng=hashSeed(seed);this.config={...DEFAULTS,...config};if(!Number.isFinite(this.config.escapeRate)||this.config.escapeRate<0)throw Error('逸散速率无效');this.year=0;this.steps=0;this.edgeFlowStep=0;this.species=SPECIES.map(s=>({...s}));this.events=[];this.eventLimit=2000;this.droppedEvents=0;this.edits=[];this.ancients={};this.lifeInput=0;this.lifeSpent=0;this.input=0;this.escaped=0;this.manual=0;this.errorAbsolute=0;
  for(const f of FIELDS)this[f]=new Float64Array(this.n);
  this.type=new Int16Array(this.n*2).fill(-1);this.count=new Uint32Array(this.n*2);this.mass=new Float64Array(this.n*2);this.qi=new Float64Array(this.n*2);this.age=new Float64Array(this.n*2);this.life=new Float64Array(this.n*2);this.seedBank=new Float64Array(this.n*SPECIES.length);this.seedAge=new Float64Array(this.n*SPECIES.length);this.stage=new Uint16Array(this.n*2);this.maturity=new Float64Array(this.n*2);this.cohortCount=new Uint32Array(this.n*16);this.cohortBirth=new Float64Array(this.n*16);this.overrides={};for(const f of ['plantAbsorb','plantProcessing','plantRoot','plantRelease'])this[f]=new Float64Array(this.n*2);this.flows={};for(const f of FLOWS)this.flows[f]=new Float64Array(this.n);this.before=new Float64Array(this.n);this.after=new Float64Array(this.n);this.gDelta=new Float64Array(this.n);this.aDelta=new Float64Array(this.n);this.births=0;this.deaths=0;
  const h=this.rng;
  generateTerrain(this,noise);
  partition(this);
  for(let y=0;y<size;y++)for(let x=0;x<size;x++){const i=y*size+x;this.sun[i]=clamp(.7+(this.height[Math.min(size-1,y+1)*size+x]-this.height[Math.max(0,y-1)*size+x])*6,.15,1);this.baseTemp[i]=this.config.climate+(y/(size-1)-.5)*this.config.climateGradient-this.height[i]*22+(this.sun[i]-.5)*7+this.heat[i];this.temp[i]=this.baseTemp[i];this.water[i]=this.baseWater[i];this.receive[i]=8+8*this.sun[i];this.efficiency[i]=.2+.65*this.rock[i];this.production[i]=.003+Math.pow(this.rock[i],5)*.5+Math.pow(this.heat[i]/12,2)*.6;this.capacity[i]=80+this.rock[i]*700;this.conduct[i]=.025+.88*this.fracture[i]+.07*(1-this.rock[i]);this.outlet[i]=.001+this.fracture[i]*(.004+this.baseWater[i]*.018+this.river[i]*.024);this.airCapacity[i]=500+this.baseWater[i]*500;this.soilCapacity[i]=5+this.baseWater[i]*25+this.rock[i]*20;this.soilBindRate[i]=.004+.012*this.rock[i];this.soilReleaseRate[i]=.005+.02*(1-this.rock[i]);this.ground[i]=this.capacity[i]*(.1+.55*noise(x/19,y/19,h+3));this.air[i]=1+this.baseWater[i]*5;this.soil[i]=this.baseWater[i]*3;
   if(this.height[i]>.23&&this.lakeDepth[i]<=.012&&this.baseTemp[i]<53){const grass=this.baseWater[i]>.55?1:0;this.establish(i,grass,Math.floor(12+this.random()*22),.5+this.random()*.6,false);if(this.random()<.44)this.establish(i,this.baseWater[i]>.55?5:4,1+Math.floor(this.random()*3),.8+this.random(),false);if(this.random()<.025)this.establish(i,2,4+Math.floor(this.random()*8),.7,false);if(this.random()<.002)this.establish(i,this.heat[i]>9?7:6,1,2+this.random()*2,false);}
   for(let l=0;l<2;l++){const k=i*2+l;if(this.type[k]>=0){this.age[k]=this.random()*this.species[this.type[k]].life*.6;this.life[k]=this.count[k]*Math.max(0,this.species[this.type[k]].life-this.age[k]);this.qi[k]=this.species[this.type[k]].spirit?this.mass[k]*this.species[this.type[k]].capacity*.2:0;const t=this.type[k];this.seedBank[i*8+t]=2;}}
  }
  for(let k=1;k<this.n*2;k+=2){if(this.count[k]===1&&this.type[k]>=6&&this.age[k]>=this.config.ancientAge&&this.mass[k]>=this.config.ancientMass)this.ancients[k]={age:this.age[k],mass:this.mass[k],qi:this.qi[k],life:this.life[k]};}
  for(let k=0;k<this.n*2;k++){this.cohortCount.fill(0,k*8,k*8+8);const count=this.count[k]-(this.ancients[k]?1:0);if(count>0){const life=this.species[this.type[k]].life;for(let a=0;a<count;a++)this.addCohort(k,1,life*(.08+.8*(a+.5)/count));}this.refreshLife(k,this.year);}
  for(let i=0;i<this.n;i++){const g=gatheringDefaults(this,i);this.groundGatherRate[i]=this.gatherRate[i]=g.rate;this.gatherLimit[i]=g.limit;}this.transportVersion=1;this.initial=this.total();this.initialLife=this.lifeTotal();this.lifeInput=0;this.lifeSpent=0;this.lastAudit={error:0,total:this.initial,input:0};this.refreshTotals();this.initializing=false;this.regions=updateRegions(this,true);
 }
 addCohort(k,count,age=0,time=this.year){const life=this.species[this.type[k]].life,birth=time-age,b=((Math.floor(birth/(life/8))%8)+8)%8,j=k*8+b,n=this.cohortCount[j];this.cohortBirth[j]=(this.cohortBirth[j]*n+birth*count)/(n+count);this.cohortCount[j]+=count;}
 refreshLife(k,time=this.year){if(this.type[k]<0){this.life[k]=this.age[k]=0;return;}const lifespan=this.species[this.type[k]].life;let life=0,ageSum=0;for(let b=0;b<8;b++){const j=k*8+b,age=Math.max(0,time-this.cohortBirth[j]);life+=this.cohortCount[j]*Math.max(0,lifespan-age);ageSum+=this.cohortCount[j]*age;}const anc=this.ancients[k];if(anc){life+=anc.life;ageSum+=anc.age;}this.life[k]=life;this.age[k]=this.count[k]?ageSum/this.count[k]:0;}
 removeCohorts(k,amount,time=this.year){let removed=0;while(amount>0){let oldest=-1;for(let b=0;b<8;b++){const j=k*8+b;if(this.cohortCount[j]&&(oldest<0||this.cohortBirth[j]<this.cohortBirth[oldest]))oldest=j;}if(oldest<0)break;const n=Math.min(amount,this.cohortCount[oldest]);this.cohortCount[oldest]-=n;removed+=n;amount-=n;}return removed;}
 random(){let x=this.rng;x^=x<<13;x^=x>>>17;x^=x<<5;this.rng=x>>>0;return this.rng/4294967296;}
 integer(v){return Math.floor(v)+(this.random()<v%1?1:0);}
 s(k){const base=this.species[this.type[k]],s=this.overrides[k]?{...base,...this.overrides[k]}:base,stage=this.stage[k]||0;if(!stage)return s;return{...s,capacity:s.capacity*Math.pow(2,stage),absorb:s.absorb*Math.pow(1.4,stage),root:s.root*Math.pow(1.4,stage)};}
 event(i,type,detail){if(this.initializing)return;this.events.push({year:this.year,step:this.steps,i,type,...detail});if(this.events.length>this.eventLimit){this.events.splice(0,500);this.droppedEvents+=500;}}
 establish(i,t,num,mass=1,log=true,context={cause:'公开建立命令'}){const k=i*2+this.species[t].layer,prior={species:this.type[k],count:this.count[k],mass:this.mass[k],qi:this.qi[k]};if(this.type[k]>=0&&this.type[k]!==t&&this.count[k])this.kill(k,'换种');this.type[k]=t;this.stage[k]=this.maturity[k]=0;this.count[k]=num;this.mass[k]=num*mass;this.age[k]=0;this.cohortCount.fill(0,k*8,k*8+8);this.addCohort(k,num);this.life[k]=num*this.species[t].life;this.lifeInput+=this.life[k];if(log)this.event(i,'建立',{species:t,layer:this.species[t].layer,count:num,before:prior,after:{species:t,count:num,mass:this.mass[k],qi:this.qi[k]},...context});}
 local(i){return this.ground[i]+this.air[i]+this.mineral[i]+this.soil[i]+this.detritus[i]+this.qi[i*2]+this.qi[i*2+1];}
 total(){let v=0;for(let i=0;i<this.n;i++)v+=this.local(i);return v;}
 lifeTotal(){let t=0;for(const v of this.life)t+=v;return t;}
 kill(k,cause='死亡',remove=false){const i=k>>1,old=this.count[k],q=this.qi[k];if(!old)return;if(remove){this.manual-=q;this.flows.edit[i]-=q;}else{this.detritus[i]+=q;this.flows.death[i]+=q;}this.lifeSpent+=this.life[k];this.event(i,cause,{species:this.type[k],layer:k%2,before:old,after:0,qi:q,life:this.life[k],cause,destination:remove?'外部移除':'遗骸'});this.cohortCount.fill(0,k*8,k*8+8);this.count[k]=0;this.mass[k]=0;this.qi[k]=0;this.life[k]=0;this.age[k]=0;delete this.ancients[k];delete this.overrides[k];this.type[k]=-1;}
 suitability(i,s,light){if(this.height[i]<.23||this.lakeDepth[i]>.012)return 0;const temp=clamp(1-Math.abs(this.temp[i]-s.temp)/s.tol),water=clamp(1-Math.abs(this.water[i]-s.water)/s.wt),sun=clamp(1-Math.abs(light-s.light)/.8);return temp*water*sun;}
 step(){this.edgeFlowStep=this.steps+1;for(const f of ['groundEast','groundSouth','airEast','airSouth'])this[f].fill(0);this.editLedger=null;for(const f of ['plantAbsorb','plantProcessing','plantRoot','plantRelease'])this[f].fill(0);const dt=this.config.dt,n=this.n,N=this.size;for(const f of FLOWS)this.flows[f].fill(0);let before=0,added=0;for(let i=0;i<n;i++){this.before[i]=this.local(i);before+=this.before[i];}this.gDelta.fill(0);this.aDelta.fill(0);
  const micro=ancientMicroclimate(this),attraction=transportQi(this);
  if(this.year+dt-(this.regions?.year??this.year)>=1-1e-8)this.ancientInfluences=observeAncients(this,micro,attraction);
  for(let i=0;i<n;i++){
   this.ground[i]+=this.gDelta[i];this.air[i]+=this.aDelta[i];
   let budget=this.receive[i]*dt;const g=Math.min(budget*this.efficiency[i],this.production[i]*dt,Math.max(0,this.capacity[i]-this.ground[i]));this.ground[i]+=g;if(g>0)budget=Math.max(0,budget-g/this.efficiency[i]);added+=g;this.flows.geology[i]=g;
   const surfaceEquilibrium=4+this.baseWater[i]*16+this.heat[i]*.8;let vent=Math.min(Math.max(0,this.ground[i]-this.capacity[i]*this.air[i]/surfaceEquilibrium)*this.outlet[i]*dt,Math.max(0,this.airCapacity[i]-this.air[i]));this.ground[i]-=vent;this.air[i]+=vent;this.flows.vent[i]=vent;
   if(this.ground[i]/this.capacity[i]>.5&&this.rock[i]>.55)this.mineralTime[i]+=dt;else this.mineralTime[i]=Math.max(0,this.mineralTime[i]-dt);
   if(this.mineralTime[i]>8){const q=Math.min(this.ground[i],Math.max(0,this.capacity[i]*2-this.mineral[i]),this.ground[i]*this.rock[i]*this.config.mineralRate*dt);if(q>0&&this.mineral[i]===0)this.event(i,'矿化',{before:0,after:q,groundBefore:this.ground[i],groundAfter:this.ground[i]-q,concentration:this.ground[i]/this.capacity[i],duration:this.mineralTime[i],rock:this.rock[i],cause:'岩性超过 0.55、地下充盈超过 0.5，累计条件超过 8 年'});this.ground[i]-=q;this.mineral[i]+=q;this.flows.bind[i]+=q;}
   let decomp=Math.min(this.detritus[i]*this.config.decompose*dt*(.25+this.water[i]),Math.max(0,this.airCapacity[i]-this.air[i]));this.detritus[i]-=decomp;this.air[i]+=decomp;this.flows.decompose[i]=decomp;
   let bind=Math.min(this.air[i]*this.soilBindRate[i]*dt,this.soilCapacity[i]-this.soil[i]);if(bind>0){this.air[i]-=bind;this.soil[i]+=bind;this.flows.bind[i]+=bind;}let weather=Math.min(this.soil[i]*this.soilReleaseRate[i]*dt,Math.max(0,this.airCapacity[i]-this.air[i]));this.soil[i]-=weather;this.air[i]+=weather;this.flows.weather[i]=weather;
   const tk=i*2+1;let cover=0;if(this.count[tk])cover=clamp(this.mass[tk]*this.s(tk).size*this.s(tk).shade/10);
   const environmentCover=Math.max(cover,micro.cover[i]);const targetT=this.baseTemp[i]-environmentCover*8*this.sun[i]*this.config.feedback,targetW=clamp(this.baseWater[i]+environmentCover*.25*this.baseWater[i]*this.config.feedback+Math.min(.08,this.detritus[i]/1000)*this.baseWater[i]*this.config.feedback);
   this.temp[i]+=(targetT-this.temp[i])*Math.min(1,dt*.4);this.water[i]+=(targetW-this.water[i])*Math.min(1,dt*.3);
   // Tree first, then grass: an explicit canopy/competition stage, not iteration-dependent.
   for(let layer=1;layer>=0;layer--){const k=i*2+layer;let count=this.count[k];if(!count)continue;const s=this.s(k),priorMass=this.mass[k],priorQi=this.qi[k],priorCount=count,tracked=this.ancients[k],light=layer?this.sun[i]:this.sun[i]*(1-cover*.85),fit=this.suitability(i,s,light),cap=this.mass[k]*s.capacity;
    let proc=Math.min(budget,Math.max(0,cap-this.qi[k]),s.process*this.mass[k]*dt*fit);if(!s.spirit)proc=0;this.qi[k]+=proc;budget-=proc;added+=proc;this.flows.processing[i]+=proc;this.plantProcessing[k]=proc;
    let root=Math.min(this.ground[i],Math.max(0,cap-this.qi[k]),s.root*this.mass[k]*dt*fit);this.ground[i]-=root;this.qi[k]+=root;this.flows.root[i]+=root;this.plantRoot[k]=root;
    let absorb=Math.min(this.air[i],Math.max(0,cap-this.qi[k]),s.absorb*this.mass[k]*dt*fit*this.air[i]/Math.max(1,s.need));this.air[i]-=absorb;this.qi[k]+=absorb;this.flows.absorb[i]+=absorb;this.plantAbsorb[k]=absorb;
    let release=Math.min(this.qi[k],(proc+root+absorb)*Math.min(1,s.release)+Math.max(0,this.qi[k]-cap*.9)*.03*dt,Math.max(0,this.airCapacity[i]-this.air[i]));this.qi[k]-=release;this.air[i]+=release;this.flows.release[i]+=release;this.plantRelease[k]=release;
    let litter=this.qi[k]*.002*dt;this.qi[k]-=litter;this.detritus[i]+=litter;this.flows.litter[i]+=litter;
    const enough=s.need?clamp((this.qi[k]/Math.max(1,this.mass[k])+this.air[i]*.08)/s.need):1,over=clamp((this.air[i]-s.tolerance)/s.tolerance),health=fit*enough*(1-over),area=layer?10:90,space=clamp(1-this.mass[k]*s.size/area);
    const growth=this.mass[k]*s.growth*health*space*dt;const supported=s.spirit?Math.max(0,this.qi[k]/Math.max(.01,s.need*(layer?2:.5))-this.mass[k]):Infinity;this.mass[k]+=Math.min(growth,supported);
    if(this.config.maturation&&s.spirit&&this.qi[k]>=cap*.7&&health>.2&&Number.isFinite(cap*2)){this.maturity[k]+=dt;if(this.maturity[k]>=8*(this.stage[k]+1)){const old=this.stage[k];this.stage[k]++;this.maturity[k]=0;this.event(i,'灵植质变',{species:this.type[k],before:old,after:this.stage[k],qi:this.qi[k],capacityBefore:cap,cause:'长期积累、适配与承载改变'});}}else this.maturity[k]=Math.max(0,this.maturity[k]-dt*.25);
    const previousLife=this.life[k],anc=this.ancients[k],protect=anc?1:0;
    if(anc){anc.age+=dt;const share=clamp(anc.mass/Math.max(priorMass,1e-9));anc.mass+=Math.max(0,this.mass[k]-priorMass)*share;anc.qi=clamp(anc.qi+(this.qi[k]-priorQi)*share,0,this.qi[k]);anc.life=Math.max(0,anc.life-dt);}
    let aged=0;for(let b=0;b<8;b++){const j=k*8+b;if(this.cohortCount[j]&&this.year+dt-this.cohortBirth[j]>=s.life)aged+=this.cohortCount[j];}
    let deaths=Math.min(count-protect,aged+this.integer((count-protect)*(Math.max(0,.25-health)*.28+over*.2)*dt));
    const ancientDies=!!anc&&(anc.life<=0||anc.age>=s.life||this.random()<(Math.max(0,.25-health)*.28+over*.2)*dt);if(ancientDies)deaths++;
    if(deaths){const normalDeaths=deaths-(ancientDies?1:0),ratio=clamp(normalDeaths/Math.max(1,count-protect)),q=(this.qi[k]-(anc?.qi||0))*ratio+(ancientDies?anc.qi:0),removedMass=(this.mass[k]-(anc?.mass||0))*ratio+(ancientDies?anc.mass:0);this.removeCohorts(k,normalDeaths,this.year+dt);this.qi[k]=Math.max(0,this.qi[k]-q);this.detritus[i]+=q;this.flows.death[i]+=q;this.mass[k]=Math.max(0,this.mass[k]-removedMass);this.count[k]-=deaths;this.deaths+=deaths;this.event(i,'种群死亡',{species:this.type[k],layer,before:count,after:this.count[k],deaths,aged,fit,health,over,qi:q,mass:removedMass,destination:'遗骸',cause:aged>=normalDeaths&&!ancientDies?'寿命耗尽':'寿命与环境风险结算'});
     if(ancientDies){delete this.ancients[k];this.event(i,'古树死亡',{species:this.type[k],layer,before:1,after:0,age:anc.age,qi:anc.qi,destination:'遗骸',cause:anc.age>=s.life?'寿命耗尽':'环境损伤'});}if(!this.count[k]){this.event(i,'种群消失',{species:this.type[k],before:count,after:0,fit,qi:q,cause:'本步死亡后无存活个体'});this.detritus[i]+=this.qi[k];this.flows.death[i]+=this.qi[k];this.lifeSpent+=previousLife;this.type[k]=-1;this.mass[k]=this.qi[k]=this.life[k]=0;this.stage[k]=this.maturity[k]=0;this.cohortCount.fill(0,k*8,k*8+8);delete this.ancients[k];delete this.overrides[k];continue;}}
    this.refreshLife(k,this.year+dt);this.lifeSpent+=Math.max(0,previousLife-this.life[k]);
    const t=this.type[k],sb=i*8+t,offspring=this.count[k]*s.fertility*health*dt;this.seedBank[sb]+=offspring; if(offspring>.01)this.seedAge[sb]=0;
    if(offspring>.02){const dir=(i+this.steps)%4,j=dir===0?(i%N?i-1:-1):dir===1?(i%N<N-1?i+1:-1):dir===2?(i>=N?i-N:-1):(i<n-N?i+N:-1);if(j>=0){this.seedBank[j*8+t]+=offspring*.2;this.seedBank[sb]-=offspring*.2;this.seedAge[j*8+t]=0;}}
    if(layer&&s.spirit&&!this.ancients[k]&&this.age[k]>=this.config.ancientAge&&this.mass[k]/this.count[k]>=this.config.ancientMass&&this.qi[k]/this.count[k]>=s.capacity){let oldest=-1;for(let b=0;b<8;b++){const j=k*8+b;if(this.cohortCount[j]&&(oldest<0||this.cohortBirth[j]<this.cohortBirth[oldest]))oldest=j;}if(oldest<0)continue;const individualAge=this.year+dt-this.cohortBirth[oldest];this.cohortCount[oldest]--;this.ancients[k]={age:individualAge,mass:this.mass[k]/this.count[k],qi:this.qi[k]/this.count[k],life:Math.max(0,s.life-individualAge)};this.event(i,'古树形成',{species:t,age:this.age[k],mass:this.ancients[k].mass,qi:this.ancients[k].qi,cause:'年龄、体型和实际积累共同满足'});}
   }
   for(let t=0;t<8;t++){const b=i*8+t;if(this.seedBank[b]<=0)continue;this.seedAge[b]+=dt;if(this.seedAge[b]>this.config.seedLife){this.seedBank[b]=0;continue;}this.seedBank[b]=Math.min(100,this.seedBank[b]);const s=this.species[t],k=i*2+s.layer;const light=s.layer?this.sun[i]:this.sun[i]*(1-cover*.85),fit=this.suitability(i,s,light),qiFit=s.need?clamp((this.air[i]+this.ground[i]*s.root*.1)/s.need):1;
    if(this.type[k]>=0&&this.type[k]!==t){const old=this.s(k);if(this.count[k]>(s.layer?1:2)||this.suitability(i,old,light)>.12)continue;}
    const area=s.layer?10:90,space=clamp(1-this.mass[k]*s.size/area);if(fit*qiFit<.18||space<.05)continue;const births=Math.min(Math.floor(this.seedBank[b]),this.integer(this.seedBank[b]*fit*qiFit*space*dt*.2));if(!births)continue;this.seedBank[b]-=births;
    if(this.type[k]!==t)this.establish(i,t,births,.1,true,{cause:'有效种源在适配环境与剩余空间中萌发',seedBefore:this.seedBank[b]+births,seedAfter:this.seedBank[b],seedAge:this.seedAge[b],fit,qiFit,space,light});else{const old=this.count[k];this.count[k]+=births;this.mass[k]+=births*.1;this.addCohort(k,births,0,this.year+dt);this.refreshLife(k,this.year+dt);this.lifeInput+=births*s.life;}this.births+=births;
   }
  }
  let escaped=0;const escapeFraction=-Math.expm1(-this.config.escapeRate*dt);
  for(let i=0;i<n;i++){const q=this.air[i]*escapeFraction;this.air[i]-=q;this.flows.escape[i]=q;escaped+=q;}
  this.escaped+=escaped;this.year+=dt;this.steps++;this.input+=added;let after=0;for(let i=0;i<n;i++){this.after[i]=this.local(i);after+=this.after[i];}const error=after-before-added+escaped;this.errorAbsolute+=Math.abs(error);this.lastAudit={before,total:after,input:added,escaped,error,cumulative:this.errorAbsolute};observeQi(this);this.regions=updateRegions(this);
 }
 refreshTotals(){let plants=0,trees=0,g=0,a=0,m=0;for(let i=0;i<this.n;i++){plants+=this.count[i*2];trees+=this.count[i*2+1];g+=this.ground[i];a+=this.air[i];m+=this.mineral[i];}this.summary={plants,trees,ground:g,air:a,mineral:m,ancients:Object.keys(this.ancients).length,escaped:this.escaped};return this.summary;}
 inspect(i){if(!Number.isInteger(i)||i<0||i>=this.n)throw Error('无效格子');const data={i,x:i%this.size,y:Math.floor(i/this.size),year:this.year,step:this.steps};const x=i%this.size,y=(i/this.size)|0;const form=landformDetails(this,i);data.landform=form.primary;data.landformFeatures=form.features;data.landformReasons=form.reasons;data.relief=Math.max(...[x?i-1:i,x<this.size-1?i+1:i,y?i-this.size:i,y<this.size-1?i+this.size:i].map(j=>Math.abs(this.height[j]-this.height[i])));for(const f of FIELDS)data[f]=this[f][i];data.plants=[0,1].map(l=>{const k=i*2+l;return{type:this.type[k],count:this.count[k],mass:this.mass[k],qi:this.qi[k],age:this.age[k],life:this.life[k],ancient:this.ancients[k]?{...this.ancients[k],stage:this.stage[k]}:null,stage:this.stage[k],maturity:this.maturity[k],flows:{absorb:this.plantAbsorb[k],processing:this.plantProcessing[k],root:this.plantRoot[k],release:this.plantRelease[k]},traits:this.type[k]>=0?this.s(k):null};});data.seeds=this.species.map((s,t)=>({name:s.name,count:this.seedBank[i*8+t],age:this.seedAge[i*8+t]})).filter(s=>s.count>.01);data.flows=Object.fromEntries(FLOWS.map(f=>[f,this.flows[f][i]]));data.before=this.before[i];data.after=this.after[i];data.ledgerSpan=this.config.dt;if(this.editLedger?.i===i&&this.editLedger.step===this.steps){data.before=this.editLedger.before;data.after=this.editLedger.after;data.flows=Object.fromEntries(FLOWS.map(f=>[f,f==='edit'?this.editLedger.delta:0]));data.ledgerSpan=0;}data.regions=regionsAt(this.regions,i);data.events=this.events.filter(e=>e.i===i).slice(-20);return data;}
 edit(cmd){const i=Number(cmd.i);if(!Number.isInteger(i)||i<0||i>=this.n)throw Error('请选择格子');let before=this.inspect(i),total=this.total();const value=Number(cmd.value);if(!Number.isFinite(value))throw Error('请输入有限数值');
  if(cmd.kind==='field'){const limits={groundGatherRate:[0,1000],gatherRate:[0,1000],gatherLimit:[.01,10000],ground:[0,this.capacity[i]],air:[0,this.airCapacity[i]],airCapacity:[Math.max(1,this.air[i]),10000],soilCapacity:[this.soil[i],10000],soilBindRate:[0,1],soilReleaseRate:[0,1],heat:[0,100],baseTemp:[-40,100],baseWater:[0,1],conduct:[0,1],outlet:[0,1],surfaceNorth:[0,1],surfaceSouth:[0,1],surfaceWest:[0,1],surfaceEast:[0,1]};if(!limits[cmd.field])throw Error('不可编辑字段');const [lo,hi]=limits[cmd.field];if(value<lo||value>hi)throw Error(`允许范围 ${lo}—${hi}`);if(cmd.field==='heat'){this.baseTemp[i]+=value-this.heat[i];this.production[i]=.003+Math.pow(this.rock[i],5)*.5+Math.pow(value/12,2)*.6;}this[cmd.field][i]=value;}
  else if(cmd.kind==='plant'){const t=Number(cmd.species);if(!this.species[t]||value<1||value>1000||!Number.isInteger(value))throw Error('无效植物或株数');if(cmd.ancient&&(!this.species[t].layer||!this.species[t].spirit))throw Error('古树必须是灵树');if(cmd.ancient&&this.ancients[i*2+1])throw Error('该格已有古树');const k=i*2+this.species[t].layer;if(this.count[k]&&this.type[k]!==t)throw Error('该层已有其他植物，请先移除');if(this.count[k]){this.count[k]+=value;this.mass[k]+=value;this.addCohort(k,value);this.life[k]+=value*this.species[t].life;this.lifeInput+=value*this.species[t].life;}else this.establish(i,t,value,1,true,{cause:'人工添加植物'});if(cmd.ancient){if(!this.species[t].layer||!this.species[t].spirit)throw Error('古树必须是灵树');const newbornBucket=((Math.floor(this.year/(this.species[t].life/8))%8)+8)%8;this.cohortCount[k*8+newbornBucket]--;this.ancients[k]={age:100,mass:3,qi:0,life:this.species[t].life-100};this.mass[k]+=2;this.refreshLife(k);this.lifeSpent+=100;}}
  else if(cmd.kind==='death'||cmd.kind==='remove'){if(![0,1].includes(Number(cmd.layer)))throw Error('无效植物层');this.kill(i*2+Number(cmd.layer),cmd.kind==='death'?'人工致死':'实验移除',cmd.kind==='remove');}
  else if(cmd.kind==='trait'){if(![0,1].includes(Number(cmd.layer)))throw Error('无效植物层');const k=i*2+Number(cmd.layer),s=this.type[k]>=0?this.s(k):null;if(!s)throw Error('该层没有植物');if(!['process','absorb','root','release','capacity'].includes(cmd.field)||value<0||value>1000)throw Error('能力范围 0—1000');if(!s.spirit&&cmd.field==='process'&&value>0)throw Error('普通植物不能加工天道之气');this.overrides[k]={...this.overrides[k],[cmd.field]:value};const cap=this.mass[k]*this.s(k).capacity;if(this.qi[k]>cap){const oldQi=this.qi[k];this.detritus[i]+=oldQi-cap;this.qi[k]=cap;if(this.ancients[k])this.ancients[k].qi*=cap/oldQi;}}
  else throw Error('未知编辑');const delta=this.total()-total;if(cmd.kind!=='remove')this.manual+=delta;this.flows.edit[i]=delta;this.editLedger={i,step:this.steps,before:before.ground+before.air+before.mineral+before.soil+before.detritus+before.plants.reduce((s,p)=>s+p.qi,0),after:this.local(i),delta};this.edits.push({year:this.year,step:this.steps,cmd:{...cmd},before,after:this.inspect(i),delta});if(this.edits.length>500)this.edits.shift();this.event(i,'人工干预',{cmd:{...cmd},delta,before:editFacts(before),after:editFacts(this.inspect(i)),cause:'用户提交的实验命令'});this.refreshTotals();return this.inspect(i);
 }
 serialize(){const out={};for(const [k,v]of Object.entries(this)){if(ArrayBuffer.isView(v))out[k]={typed:v.constructor.name,data:Array.from(v)};else if(k==='flows')out.flows=Object.fromEntries(FLOWS.map(f=>[f,Array.from(v[f])]));else out[k]=v;}return out;}
 static load(data){
  if(data?.version!==VERSION||!Number.isInteger(data.size)||data.n!==data.size**2||![16,32,64,128,256].includes(data.size))throw Error('存档版本或地图无效');
  const migratedDefaults={groundGatherRate:0,gatherRate:0,gatherLimit:2,sourceMean:0,throughputMean:0,gatherMean:0,airCapacity:500,soilCapacity:30,soilBindRate:.008,soilReleaseRate:.015};
  const w=Object.create(World.prototype),types={Float64Array,Int16Array,Int32Array,Uint32Array,Uint8Array,Uint16Array},expected={};
  for(const f of FIELDS)expected[f]=data.n;for(const f of ['type','count','mass','qi','age','life','stage','maturity'])expected[f]=data.n*2;for(const f of ['seedBank','seedAge'])expected[f]=data.n*8;for(const f of ['cohortCount','cohortBirth'])expected[f]=data.n*16;for(const f of ['before','after','gDelta','aDelta'])expected[f]=data.n;
  for(const[k,length]of Object.entries(expected)){const v=data[k]??(k in migratedDefaults?{typed:'Float64Array',data:Array.from({length:data.n},(_,i)=>k==='soilCapacity'?Math.max(data.soil?.data?.[i]||0,(data.water?.data?.[i]||0)*30):migratedDefaults[k])}:['surfaceNorth','surfaceSouth','surfaceWest','surfaceEast'].includes(k)?{typed:'Float64Array',data:Array(data.n).fill(1)}:['lakeDepth','lakeIsland','fracture','groundEast','groundSouth','airEast','airSouth'].includes(k)?{typed:'Float64Array',data:Array(data.n).fill(0)}:undefined),allowed=k==='type'?['Int16Array']:['count','cohortCount'].includes(k)?['Uint32Array']:k==='stage'?['Uint8Array','Uint16Array']:['Float64Array'];if(!v||!allowed.includes(v.typed)||!types[v.typed]||!Array.isArray(v.data)||v.data.length!==length||v.data.some(x=>!Number.isFinite(x)))throw Error('存档字段损坏：'+k);if(['count','mass','qi','life','seedBank','seedAge','ground','air','mineral','soil','detritus'].includes(k)&&v.data.some(x=>x<0))throw Error('存档含负库存');if(k==='type'&&v.data.some(x=>!Number.isInteger(x)||x< -1||x>=SPECIES.length))throw Error('植物编号无效');if(k==='count'&&v.data.some(x=>!Number.isInteger(x)))throw Error('株数无效');w[k]=new types[v.typed](v.data);}
  for(const k of ['year','steps','rng','input','manual','initial','initialLife','lifeInput','lifeSpent','errorAbsolute','births','deaths','droppedEvents'])if(!Number.isFinite(data[k]))throw Error('存档时钟或账目损坏');
  for(const[k,v]of Object.entries(data.config||{}))if(!(k in DEFAULTS)||!Number.isFinite(v))throw Error('存档配置损坏');if(data.config?.dt<=0||data.config?.dt>1)throw Error('存档步长无效');
  if(!Array.isArray(data.species)||data.species.length!==SPECIES.length)throw Error('物种表损坏');for(let t=0;t<SPECIES.length;t++){const s=data.species[t];if(s.layer!==SPECIES[t].layer||s.spirit!==SPECIES[t].spirit)throw Error('物种类别无效');for(const k of Object.keys(SPECIES[t]))if(typeof SPECIES[t][k]==='number'&&!Number.isFinite(s[k]))throw Error('物种参数无效');if(!s.spirit&&s.process!==0)throw Error('普通植物加工能力无效');}
  const scalar=['version','size','n','seed','rng','config','year','steps','species','eventLimit','droppedEvents','lifeInput','lifeSpent','input','manual','errorAbsolute','births','deaths','initial','initialLife','lastAudit','summary','editLedger'];for(const k of scalar)w[k]=structuredClone(data[k]);
  for(const f of ['plantAbsorb','plantProcessing','plantRoot','plantRelease']){const v=data[f];if(v!==undefined&&(!Array.isArray(v.data)||v.data.length!==w.n*2||v.data.some(x=>!Number.isFinite(x)||x< -1e-9)))throw Error('植物收支损坏');w[f]=v?Float64Array.from(v.data,x=>Math.max(0,x)):new Float64Array(w.n*2);}
  for(const [f,T]of [['drainage',Int32Array],['catchment',Float64Array]]){const v=data[f];if(v!==undefined&&(!Array.isArray(v.data)||v.data.length!==w.n||v.data.some(x=>!Number.isFinite(x))))throw Error('水系数据损坏');w[f]=v?T.from(v.data):new T(w.n).fill(f==='drainage'?-1:0);}
  w.qiChannels=Array.isArray(data.qiChannels)?data.qiChannels.filter(r=>Array.isArray(r.points)&&r.points.length<10000&&r.points.every(p=>Array.isArray(p)&&p.length===2&&p.every(v=>Number.isFinite(v)&&v>=0&&v<=w.size))).map(r=>({points:r.points.map(p=>[...p])})):[];
  w.terrainFeatures=Array.isArray(data.terrainFeatures)?data.terrainFeatures.filter(f=>Number.isFinite(f.x)&&Number.isFinite(f.y)&&typeof f.label==='string').map(f=>({...f})):[];
  w.edgeFlowStep=Number.isInteger(data.edgeFlowStep)?data.edgeFlowStep:0;w.stage=Uint16Array.from(w.stage);
  w.config={...DEFAULTS,...w.config};w.escaped=data.escaped??0;if(!Number.isFinite(w.escaped)||w.escaped<0||w.config.escapeRate<0)throw Error('逸散账目或速率无效');
  w.events=Array.isArray(data.events)?structuredClone(data.events.slice(-2000)):[];w.edits=Array.isArray(data.edits)?structuredClone(data.edits.slice(-500)):[];w.eventLimit=2000;w.ancients={};for(const[k,v]of Object.entries(data.ancients||{})){const index=Number(k);if(!Number.isInteger(index)||index<0||index>=w.n*2||index%2!==1||w.count[index]<1||!w.species[w.type[index]]?.spirit)throw Error('古树记录无效');for(const f of ['age','mass','qi','life'])if(!Number.isFinite(v[f])||v[f]<0)throw Error('古树数值无效');w.ancients[index]={...v};}
  w.overrides={};for(const[k,v]of Object.entries(data.overrides||{})){const index=Number(k);if(!Number.isInteger(index)||index<0||index>=w.n*2||w.type[index]<0)throw Error('能力覆盖无效');for(const[f,value]of Object.entries(v))if(!['process','absorb','root','release','capacity'].includes(f)||!Number.isFinite(value)||value<0||value>1000||(!w.species[w.type[index]].spirit&&f==='process'&&value>0))throw Error('能力覆盖无效');w.overrides[index]={...v};}
  w.flows={};for(const f of FLOWS){const v=data.flows?.[f]??(f==='escape'?Array(w.n).fill(0):undefined);if(!Array.isArray(v)||v.length!==w.n||v.some(x=>!Number.isFinite(x)))throw Error('收支损坏');w.flows[f]=Float64Array.from(v);}if(!data.gatherRate)for(let i=0;i<w.n;i++){const g=gatheringDefaults(w,i);w.groundGatherRate[i]=w.gatherRate[i]=g.rate;w.gatherLimit[i]=g.limit;}if(!data.groundGatherRate)w.groundGatherRate.set(w.gatherRate);w.transportVersion=1;if(data.transportVersion!==1){w.edgeFlowStep=0;for(const f of ['groundEast','groundSouth','airEast','airSouth'])w[f].fill(0);}validateState(w);w.regions=restoreRegions(w,data.regions);w.ancientInfluences=[];return w;
 }
}

function editFacts(d){return{ground:d.ground,air:d.air,airCapacity:d.airCapacity,soilCapacity:d.soilCapacity,soilBindRate:d.soilBindRate,soilReleaseRate:d.soilReleaseRate,heat:d.heat,baseTemp:d.baseTemp,baseWater:d.baseWater,conduct:d.conduct,outlet:d.outlet,detritus:d.detritus,plants:d.plants.map(p=>({type:p.type,count:p.count,mass:p.mass,qi:p.qi,traits:p.traits?{...p.traits}:null}))};}
