import test from 'node:test';import assert from 'node:assert/strict';import {World,FIELDS} from '../src/world.js';
function run(w,n){for(let i=0;i<n;i++)w.step();return w;}
test('R01/02 conservative transfer, finite positive state over 50 years',()=>{const w=run(new World(16,'audit'),200);assert.ok(Math.abs(w.total()-w.initial-w.input-w.manual+w.escaped)<1e-6);for(const f of ['ground','air','mineral','soil','detritus','qi','mass','life'])for(const v of w[f])assert.ok(Number.isFinite(v)&&v>=-1e-9,`${f}: ${v}`);});
test('R05 province labels never affect simulation',()=>{const a=new World(16,'province'),b=new World(16,'province');b.province.fill(9);run(a,20);run(b,20);assert.deepEqual(a.ground,b.ground);assert.deepEqual(a.count,b.count);assert.equal(a.rng,b.rng);});
test('R16 save restore reproduces future',()=>{const a=run(new World(16,'save'),10),b=World.load(JSON.parse(JSON.stringify(a.serialize())));run(a,20);run(b,20);for(const f of [...FIELDS,'count','mass','qi','life','seedBank'])assert.deepEqual(a[f],b[f],f);assert.equal(a.rng,b.rng);assert.equal(a.escaped,b.escaped);});
test('R13 death returns only acquired qi',()=>{const w=new World(16,'death');w.kill(1);w.edit({i:0,kind:'plant',species:6,value:1});const k=1;w.qi[k]=50;const before=w.local(0),prior=w.detritus[0];w.kill(k);assert.equal(w.local(0),before);assert.equal(w.detritus[0]-prior,50);assert.equal(w.life[k],0);});
test('ordinary plants cannot be edited to process heaven qi',()=>{const w=new World(16);w.kill(0);w.height[0]=.4;w.establish(0,0,2);assert.throws(()=>w.edit({i:0,kind:'trait',layer:0,field:'process',value:10}));});
test('no seed source, no spontaneous plant generation',()=>{const w=new World(16,'empty');for(let k=0;k<w.n*2;k++)w.kill(k);w.seedBank.fill(0);run(w,40);assert.equal(w.count.reduce((a,b)=>a+b),0);assert.ok(w.input>0);});
test('invalid save rejected',()=>assert.throws(()=>World.load({version:'0.1.0',size:256,n:65536})));
test('R09 cohort turnover preserves live count and positive lifespan',()=>{const w=new World(16,'cohorts');for(let k=0;k<w.n*2;k++)w.kill(k);w.seedBank.fill(0);w.height[0]=.4;w.establish(0,0,32);w.cohortCount.fill(0,0,8);for(let b=0;b<8;b++)w.addCohort(0,4,b*.45);w.refreshLife(0);w.temp[0]=w.baseTemp[0]=23;w.water[0]=w.baseWater[0]=.24;w.sun[0]=.85;w.species[0].fertility=0;const counts=[];for(let j=0;j<16;j++){w.step();counts.push(w.count[0]);assert.equal(w.count[0],w.cohortCount.slice(0,8).reduce((a,b)=>a+b));}assert.ok(counts.some(v=>v>0&&v<32));});
test('R12 ancient is counted once and survives unrelated ordinary cohort death',()=>{const w=new World(16,'ancient');w.kill(1);w.height[0]=.4;w.establish(0,6,2);w.removeCohorts(1,1);w.ancients[1]={age:100,mass:1,qi:0,life:380};w.temp[0]=w.baseTemp[0]=21;w.water[0]=w.baseWater[0]=.55;w.sun[0]=.75;for(let t=0;t<20;t++){w.step();assert.equal(w.count[1],w.cohortCount.slice(8,16).reduce((a,b)=>a+b)+(w.ancients[1]?1:0));}});
test('invalid ancient edit is rejected before mutation',()=>{const w=new World(16);const before=w.serialize();assert.throws(()=>w.edit({i:0,kind:'plant',species:0,value:1,ancient:true}));assert.deepEqual(w.serialize(),before);});
test('negative save data never replaces a world',()=>{const w=new World(16);const save=w.serialize();save.ground.data[0]=-1;assert.throws(()=>World.load(save));});
test('R20 surface backpressure stops one-way venting without deleting qi',()=>{const w=new World(16);for(let k=0;k<w.n*2;k++)w.kill(k);w.seedBank.fill(0);w.air.fill(100);w.production.fill(0);w.config.surfaceDiffusion=0;w.config.groundDiffusion=0;w.step();assert.equal(w.flows.vent.reduce((a,b)=>a+b),0);assert.ok(Math.abs(w.lastAudit.error)<1e-6);});
test('R21 maturation increases capacity without creating qi',()=>{const w=new World(16);w.kill(1);w.height[0]=.4;w.establish(0,6,1,2);w.qi[1]=199;w.overrides[1]={process:0,absorb:0,root:0,release:0};w.temp[0]=w.baseTemp[0]=21;w.water[0]=w.baseWater[0]=.55;w.sun[0]=.75;w.species[6].growth=0;w.species[6].fertility=0;const old=w.s(1).capacity;for(let j=0;j<40;j++)w.step();assert.ok(w.stage[1]>=1);assert.ok(w.s(1).capacity>old);assert.ok(w.qi[1]<=199);});
test('R01 per-cell budgets explain changes, not only global total',()=>{const w=new World(16,'local-budget');for(let t=0;t<80;t++){w.step();for(let i=0;i<w.n;i++){const f=w.flows,net=f.geology[i]+f.processing[i]+f.groundIn[i]-f.groundOut[i]+f.surfaceIn[i]-f.surfaceOut[i]-f.escape[i];assert.ok(Math.abs(w.after[i]-w.before[i]-net)<1e-7,`cell ${i}`);}}});
test('edit ledger is distinct from previous simulation step',()=>{const w=new World(16);w.step();w.edit({i:0,kind:'field',field:'air',value:50});const d=w.inspect(0);assert.equal(d.ledgerSpan,0);assert.ok(Math.abs(d.after-d.before-d.flows.edit)<1e-8);assert.equal(d.flows.geology,0);w.step();assert.equal(w.inspect(0).ledgerSpan,.25);});

function isolatedQi(){const w=new World(16,'escape');for(let k=0;k<w.n*2;k++)w.kill(k);w.seedBank.fill(0);for(const f of ['air','ground','soil','detritus','mineral','production','outlet','baseWater','water','soilBindRate','soilReleaseRate'])w[f].fill(0);w.config.surfaceDiffusion=w.config.groundDiffusion=w.config.decompose=w.config.mineralRate=0;return w;}
test('R22 unbound qi escapes exponentially, stored qi is retained',()=>{const w=isolatedQi();w.air[0]=100;w.ground[0]=80;w.mineral[0]=40;w.detritus[0]=30;const before=w.total();run(w,40);assert.ok(Math.abs(w.air[0]-100*Math.exp(-.06*10))<1e-9);assert.equal(w.ground[0],80);assert.equal(w.mineral[0],40);assert.equal(w.detritus[0],30);assert.ok(Math.abs(before-w.total()-w.escaped)<1e-9);});
test('R22 stable input approaches balance with escape',()=>{const w=isolatedQi();w.ground[0]=100;w.capacity[0]=200;w.production[0]=1;w.outlet[0]=.1;run(w,16000);const old=w.air[0];run(w,4000);assert.ok(Math.abs(w.air[0]-old)<1e-5);assert.ok(w.air[0]>0&&w.air[0]<30);assert.ok(Math.abs(w.lastAudit.input-w.lastAudit.escaped)<1e-5);});
test('R22 old saves migrate with no invented historical escape',()=>{const w=new World(16);const data=w.serialize();delete data.escaped;delete data.config.escapeRate;delete data.flows.escape;const loaded=World.load(data);assert.equal(loaded.escaped,0);assert.equal(loaded.config.escapeRate,.06);loaded.step();assert.ok(loaded.escaped>0);});
