import test from 'node:test';import assert from 'node:assert/strict';
import {flowRoutes,flowSegmentAllowed,flowSeeds} from '../src/flow-routes.js';
test('capped seed prefix covers two dimensions without selecting whole columns',()=>{const points=flowSeeds(256).slice(0,512),bins=new Uint16Array(64),columns=new Uint16Array(64);for(const [x,y]of points){bins[Math.floor(y/32)*8+Math.floor(x/32)]++;columns[Math.floor(x/4)]++;}assert.ok(bins.every(v=>v>=4));assert.ok(columns.every(v=>v>=6&&v<=10));assert.equal(new Set(points.map(p=>p[0])).size,512);assert.deepEqual(flowSeeds(256),flowSeeds(256));});
function field(){const n=16,map={};for(const p of ['ground','air'])for(const d of ['East','South'])map[p+d]=new Float64Array(n*n);return{size:n,map,edgeFlowStep:1,qiChannels:[{points:[[0,0],[16,16]]}]};}
function verify(state,prefix){const r=flowRoutes(state,prefix);assert.ok(r.routes.length);for(const route of r.routes)for(let j=1;j<route.points.length;j++)assert.ok(flowSegmentAllowed(state,prefix,route.points[j-1],route.points[j]),JSON.stringify(route.points.slice(j-1,j+1)));return r;}
test('no actual flow draws no route even with geological guide geometry',()=>{const s=field();assert.equal(flowRoutes(s,'ground').routes.length,0);s.map.groundEast.fill(1);s.edgeFlowStep=0;assert.equal(flowRoutes(s,'ground').routes.length,0);});
test('both media draw deterministic continuous routes in actual transport direction',()=>{for(const p of ['ground','air']){const s=field();s.map[p+'East'].fill(1);const r=verify(s,p);assert.ok(r.routes.some(r=>r.points.at(-1)[0]-r.points[0][0]>10));for(const route of r.routes)for(let j=1;j<route.points.length;j++)assert.ok(route.points[j][0]>=route.points[j-1][0]);assert.deepEqual(flowRoutes(s,p),r);s.qiChannels=[];assert.deepEqual(flowRoutes(s,p),r);}});
test('streamlines cannot cross a zero-flow wall, including corner shortcuts',()=>{const s=field();s.map.airEast.fill(1);s.map.airSouth.fill(.5);for(let y=0;y<16;y++)s.map.airEast[y*16+7]=0;const r=verify(s,'air');for(const route of r.routes){const xs=route.points.map(p=>p[0]);assert.ok(!(Math.min(...xs)<8&&Math.max(...xs)>=8));}assert.equal(flowSegmentAllowed(s,'air',[7.9,4.9],[8.1,5.1]),false);});
test('sink-directed field converges rather than drawing through the sink',()=>{const s=field(),center=8.3;for(let y=0;y<16;y++)for(let x=0;x<16;x++){s.map.airEast[y*16+x]=center-x-1;s.map.airSouth[y*16+x]=center-y-1;}const r=verify(s,'air');for(const route of r.routes){const distance=p=>Math.hypot(p[0]-center,p[1]-center);assert.ok(distance(route.points.at(-1))<distance(route.points[0]));for(let j=1;j<route.points.length;j++)assert.ok(distance(route.points[j])<=distance(route.points[j-1])+1e-8);}});
