import test from 'node:test';import assert from 'node:assert/strict';
import {updateRegions,regionsAt,significantRegions,restoreRegions} from '../src/regions.js';
import {World} from '../src/world.js';
function fixture(){const w={size:16,n:256,year:0,species:[{name:'乔木',size:1,spirit:false}],ancients:{}};for(const f of ['height','lakeDepth','temp','water','heat','river'])w[f]=new Float64Array(256);w.height.fill(.5);w.temp.fill(20);w.water.fill(.5);w.type=new Int16Array(512).fill(-1);w.mass=new Float64Array(512);w.count=new Uint32Array(512);return w;}
function patch(w,{forest=false,cold=false}={}){for(let y=3;y<11;y++)for(let x=3;x<11;x++){const i=y*16+x;if(forest){w.type[i*2+1]=0;w.count[i*2+1]=5;w.mass[i*2+1]=5;}if(cold)w.temp[i]=0;}}
test('multiple dimensions overlap and hostile composites do not become blessed places',()=>{const w=fixture();patch(w,{forest:true,cold:true});w.regions=updateRegions(w,true);const at=regionsAt(w.regions,5*16+5);assert.deepEqual(new Set(at.map(r=>r.dimension)),new Set(['forest','thermal','landform']));const composite=significantRegions(w.regions);assert.ok(composite.some(r=>r.label==='寒冷林区'));assert.ok(!JSON.stringify(w.regions).includes('洞天'));});
test('small patches do not become regions and newly formed forest waits five years',()=>{const w=fixture();w.type[1]=0;w.mass[1]=5;w.count[1]=5;w.regions=updateRegions(w,true);assert.equal(w.regions.items.filter(r=>r.dimension==='forest').length,0);patch(w,{forest:true});for(let year=1;year<=6;year++){w.year=year;w.regions=updateRegions(w);assert.equal(w.regions.items.find(r=>r.kind==='forest').status,year<6?'candidate':'established');}assert.equal(w.regions.items.find(r=>r.kind==='forest').formed,6);});
test('identity and unknown initial history survive continuation and save; disappearance is delayed',()=>{const w=fixture();patch(w,{forest:true});w.regions=updateRegions(w,true);const id=w.regions.items.find(r=>r.kind==='forest').id;w.year=1;w.regions=updateRegions(w);assert.equal(w.regions.items.find(r=>r.kind==='forest').id,id);assert.equal(w.regions.items.find(r=>r.kind==='forest').formed,null);w.regions=restoreRegions(w,JSON.parse(JSON.stringify(w.regions)));w.mass.fill(0);for(let y=2;y<=6;y++){w.year=y;w.regions=updateRegions(w);if(y<6){assert.equal(w.regions.items.find(r=>r.kind==='forest').id,id);assert.equal(w.regions.items.find(r=>r.kind==='forest').status,'fading');}else assert.equal(w.regions.items.filter(r=>r.dimension==='forest').length,0);}});
test('water separates regions and region tracking does not change atomic arrays',()=>{const w=fixture();patch(w,{forest:true});for(let y=3;y<11;y++)w.lakeDepth[y*16+7]=1;const before=w.mass.slice();w.regions=updateRegions(w,true);assert.equal(w.regions.items.filter(r=>r.dimension==='forest').length,2);assert.deepEqual(w.mass,before);assert.equal(regionsAt(w.regions,5*16+7).length,0);const previous=JSON.stringify(w.regions);assert.equal(JSON.stringify(updateRegions(w)),previous);});
test('malformed region save is rejected',()=>{const w=fixture();patch(w,{forest:true});const r=updateRegions(w,true);r.items[0].cells[0]=999;assert.throws(()=>restoreRegions(w,r));});
test('saved region identity and timing continue identically independent of inspection',()=>{const a=new World(16,'region-save');for(let i=0;i<13;i++)a.step();const b=World.load(JSON.parse(JSON.stringify(a.serialize())));for(let i=0;i<24;i++){a.inspect(12);a.step();b.step();}assert.deepEqual(a.regions,b.regions);assert.equal(a.rng,b.rng);const old=a.serialize();delete old.regions;const loaded=World.load(old);assert.ok(loaded.regions.items.every(r=>r.formed===null));});
test('small distinctive overlap does not promote a whole plain into a composite',()=>{const w=fixture();patch(w,{cold:true});w.regions=updateRegions(w,true);const pieces=significantRegions(w.regions);assert.ok(pieces.length);assert.ok(pieces.every(r=>r.area<=64));assert.ok(pieces.every(r=>r.cells.every(i=>w.temp[i]<=5)));});
