import test from 'node:test';
import assert from 'node:assert/strict';
import {World,FLOWS} from '../src/world.js';
function fixture(){const w=new World(16,'rules',{escapeRate:0,groundDiffusion:0,surfaceDiffusion:0});for(let k=0;k<w.n*2;k++)w.kill(k);w.seedBank.fill(0);for(const f of ['ground','air','soil','mineral','detritus','production','outlet'])w[f].fill(0);w.height.fill(.4);w.baseTemp.fill(21);w.temp.fill(21);w.baseWater.fill(.55);w.water.fill(.55);w.sun.fill(.75);w.receive.fill(100);w.efficiency.fill(.8);w.capacity.fill(1000);w.rock.fill(.3);w.events=[];return w;}
const steps=(w,n)=>{for(let i=0;i<n;i++)w.step();return w;};
test('R03 processing, root uptake and air uptake affect their own source',()=>{for(const channel of ['process','root','absorb']){const w=fixture();w.establish(0,6,1);w.species[6].shade=0;w.overrides[1]={process:0,root:0,absorb:0,release:0,[channel]:4};w.ground[0]=50;w.air[0]=20;w.step();assert.ok(w.qi[1]>0);for(const [name,flow]of [['process','processing'],['root','root'],['absorb','absorb']])assert.equal(w.flows[flow][0]>0,name===channel);}});
test('R20 reception, production, efficiency and capacity independently limit ground input',()=>{const sample=changes=>{const w=fixture();w.production[0]=100;for(const [k,v]of Object.entries(changes))w[k][0]=v;w.step();return w;};assert.equal(sample({receive:2}).flows.geology[0],.4);assert.equal(sample({production:2}).flows.geology[0],.5);assert.equal(sample({efficiency:.1}).flows.geology[0],2.5);assert.equal(sample({ground:999.9}).ground[0],1000);assert.equal(sample({ground:1000}).flows.geology[0],0);});
test('R20 zero conversion is a valid nonproducing geological cell',()=>{const w=fixture();w.establish(0,6,1);w.production[0]=10;w.efficiency[0]=0;w.step();assert.equal(w.flows.geology[0],0);assert.ok(Number.isFinite(w.qi[1]));assert.ok(w.plantProcessing[1]>0);});
test('R04 reducing plant capacity returns surplus to detritus without losing mass',()=>{const w=fixture();w.establish(0,6,1);w.qi[1]=90;const before=w.total();w.edit({i:0,kind:'trait',layer:1,field:'capacity',value:20});assert.equal(w.qi[1],20);assert.equal(w.detritus[0],70);assert.equal(w.total(),before);});
test('R08 a healthy established layer rejects a competing species',()=>{const w=fixture();w.establish(0,0,40);w.seedBank[1]=50;w.species[0].temp=21;w.species[0].water=.55;w.species[0].light=.75;w.species[0].fertility=0;steps(w,4);assert.equal(w.type[0],0);assert.ok(w.count[0]>2);});
test('R10 seed banks expire without suitable conditions, no spontaneous restoration',()=>{const w=fixture();w.seedBank[0]=50;w.baseTemp.fill(100);w.temp.fill(100);steps(w,52);assert.equal(w.seedBank[0],0);w.baseTemp.fill(21);w.temp.fill(21);steps(w,20);assert.equal(w.count.reduce((a,b)=>a+b),0);});
test('R10 new neighboring seeds come from living reproductive plants',()=>{const w=fixture();w.establish(17,0,20);w.species[0].temp=21;w.species[0].water=.55;w.species[0].light=.75;w.step();assert.ok([1,16,18,33].some(i=>w.seedBank[i*8]>0));assert.equal(w.seedBank[(15*16+15)*8],0);});
test('R11 thermal, moisture, light and high-qi tolerances change growth or survival',()=>{for(const kind of ['temperature','moisture','light','excess']){const a=fixture(),b=fixture();for(const w of [a,b]){w.establish(0,2,50);w.qi[0]=100;w.species[2].fertility=0;w.species[2].temp=21;w.species[2].water=.55;w.species[2].light=.75;if(kind==='excess')w.species[2].absorb=0;}if(kind==='temperature')b.baseTemp[0]=b.temp[0]=100;if(kind==='moisture')b.baseWater[0]=b.water[0]=0;if(kind==='light')b.sun[0]=0;if(kind==='excess')b.air[0]=500;steps(a,20);steps(b,20);assert.ok(a.mass[0]>b.mass[0],kind);}});
test('R14 mineral formation needs duration and deducts ground inventory',()=>{const w=fixture();w.rock[0]=.9;w.ground[0]=900;steps(w,32);assert.equal(w.mineral[0],0);const old=w.ground[0];w.step();assert.ok(w.mineral[0]>0);assert.ok(Math.abs(old-w.ground[0]-w.mineral[0])<1e-8);});
test('R15 microclimate relaxes after tree death while geothermal background stays fixed',()=>{const w=fixture();w.establish(0,6,1,4);w.species[6].growth=w.species[6].fertility=0;w.qi[1]=300;w.heat[0]=15;steps(w,20);assert.ok(w.temp[0]<w.baseTemp[0]);const old=w.temp[0];w.kill(1);w.step();assert.ok(w.temp[0]>old&&w.temp[0]<w.baseTemp[0]);assert.equal(w.heat[0],15);});
test('R17 observing arbitrary cells never changes future state or random stream',()=>{const a=new World(16,'observation'),b=new World(16,'observation');for(let j=0;j<40;j++){for(const i of [0,17,100,255])a.inspect(i);a.refreshTotals();a.step();b.step();}assert.equal(a.rng,b.rng);assert.deepEqual(a.ground,b.ground);assert.deepEqual(a.qi,b.qi);assert.deepEqual(a.count,b.count);});
test('R19 innate life account balances births, aging and deaths separately',()=>{const w=new World(16,'life-ledger');steps(w,200);assert.ok(Math.abs(w.lifeTotal()-w.initialLife-w.lifeInput+w.lifeSpent)<1e-5);});
test('per-plant uptake adds to per-cell ledger and survives save/load',()=>{const w=new World(16,'layers');w.step();for(let i=0;i<w.n;i++)for(const [field,flow]of [['plantProcessing','processing'],['plantAbsorb','absorb'],['plantRoot','root'],['plantRelease','release']])assert.ok(Math.abs(w[field][i*2]+w[field][i*2+1]-w.flows[flow][i])<1e-10);const b=World.load(w.serialize());assert.deepEqual(b.plantAbsorb,w.plantAbsorb);});

test('R23 higher ambient concentration increases realized uptake without exceeding source or capacity',()=>{const sample=air=>{const w=fixture();w.establish(0,6,1);w.species[6].shade=0;w.overrides[1]={process:0,root:0,absorb:1,release:0};w.air[0]=air;w.step();return w;};const low=sample(2),high=sample(20);assert.ok(high.plantAbsorb[1]>low.plantAbsorb[1]*5);assert.ok(high.plantAbsorb[1]<=20);assert.ok(high.qi[1]<=high.mass[1]*high.s(1).capacity);});
test('R23 seventh structural stage is reachable with sustained actual reserves',()=>{const w=fixture();w.establish(0,6,1,2);w.stage[1]=6;w.qi[1]=2*w.s(1).capacity*.8;w.maturity[1]=56-.25;w.species[6].shade=w.species[6].growth=w.species[6].fertility=0;w.overrides[1]={process:0,root:0,absorb:0,release:0};const total=w.total();w.step();assert.equal(w.stage[1],7);assert.ok(Math.abs(w.total()-total)<1e-7);});

test('R02/U10 malformed capacity, configuration, cohorts and ancient subsets are rejected',()=>{for(const corrupt of [s=>s.capacity.data[0]=0,s=>s.config.decompose=-1,s=>s.count.typed='Uint8Array',s=>s.cohortCount.data[0]++,s=>s.drainage.data[0]=s.n,s=>s.species[0].life=0]){const w=new World(16,'validation'),save=w.serialize();corrupt(save);assert.throws(()=>World.load(save));}});

test('saved floating point residuals do not make a valid plant ledger unloadable',()=>{const w=new World(16,'roundoff'),s=w.serialize();s.plantProcessing.data[0]=-4.440892098500626e-16;assert.equal(World.load(s).plantProcessing[0],0);s.plantProcessing.data[0]=-.001;assert.throws(()=>World.load(s));});

test('R18 establishment, mineral onset and edits retain actual before/after facts',()=>{
 const w=fixture();w.establish(0,6,1,1,true,{cause:'人工添加植物'});const born=w.events.at(-1);assert.equal(born.before.count,0);assert.equal(born.after.count,1);assert.equal(born.layer,1);
 w.edit({i:0,kind:'field',field:'air',value:25});const edit=w.events.at(-1);assert.equal(edit.before.air,0);assert.equal(edit.after.air,25);assert.equal(edit.delta,25);assert.equal(edit.i,0);assert.equal(edit.year,0);
 const m=fixture();m.ground[0]=900;m.rock[0]=.9;steps(m,33);const mineral=m.events.find(e=>e.type==='矿化');assert.ok(mineral.after>0);assert.ok(Math.abs(mineral.groundBefore-mineral.groundAfter-mineral.after)<1e-8);assert.ok(mineral.duration>8);
});
test('R18 natural deaths carry population delta, transferred qi and risk conditions',()=>{
 const w=fixture();w.establish(0,2,50);w.qi[0]=100;w.baseTemp[0]=w.temp[0]=100;steps(w,20);const deaths=w.events.filter(e=>e.type==='种群死亡');assert.ok(deaths.length);for(const e of deaths){assert.equal(e.before-e.after,e.deaths);assert.equal(e.destination,'遗骸');assert.ok(Number.isFinite(e.fit)&&Number.isFinite(e.health)&&Number.isFinite(e.over));assert.ok(e.qi>=0);}
});
