import test from 'node:test';import assert from 'node:assert/strict';import {World} from '../src/world.js';import {landformAt,landformDetails} from '../src/landforms.js';
test('terrain seed reproduces continuous coast, mountains and derived drainage',()=>{const a=new World(64,'landform'),b=new World(64,'landform'),c=new World(64,'different');assert.deepEqual(a.height,b.height);assert.deepEqual(a.drainage,b.drainage);assert.notDeepEqual(a.height,c.height);assert.ok(a.height.some(v=>v<.23));assert.ok(a.height.some(v=>v>.7));assert.ok(a.river.some(v=>v>0));for(let i=0;i<a.n;i++){let at=i,steps=0;while(a.drainage[at]>=0){const next=a.drainage[at];assert.ok(a.height[at]>=a.height[next]-1e-8);at=next;assert.ok(++steps<a.n,'drainage cycle');}}});
test('north-south temperature gradient adds the declared climate difference',()=>{const a=new World(32,'climate',{climateGradient:0}),b=new World(32,'climate',{climateGradient:40});for(const y of [0,8,16,31]){const i=y*32+16;assert.ok(Math.abs(b.baseTemp[i]-a.baseTemp[i]-(y/31-.5)*40)<1e-9);}assert.deepEqual(a.height,b.height);});
test('terrain descriptors identify actual terrain and survive saves',()=>{const w=new World(64,'labels');assert.ok(w.terrainFeatures.length>0);for(const f of w.terrainFeatures){const h=w.height[f.y*w.size+f.x];if(f.kind==='mountain')assert.ok(h>.63);if(f.kind==='sea')assert.ok(h<.15);assert.ok(['连绵山脉','辽阔海域','开阔平原','幽静湖泊','辽阔高原','低洼盆地','起伏丘陵','孤立湖岛'].includes(f.label));}const loaded=World.load(w.serialize());assert.deepEqual(loaded.terrainFeatures,w.terrainFeatures);assert.deepEqual(loaded.drainage,w.drainage);});

test('regional classification separates high plateaus, low plains, hills and enclosed basins',()=>{const w=new World(64,'classification');w.river.fill(0);w.lakeDepth.fill(0);const i=32*64+32;w.height.fill(.65);assert.equal(landformAt(w,i),'高原');w.height.fill(.35);assert.equal(landformAt(w,i),'平原');w.height.fill(.5);assert.equal(landformAt(w,i),'丘陵');w.height.fill(.6);w.height[i]=.4;assert.equal(landformAt(w,i),'盆地');});
test('lake islands are dry cells enclosed by lake water',()=>{const w=new World(256,'青野-001',{climate:24,rain:.5});const ids=Array.from(w.lakeIsland).flatMap((v,i)=>v?[i]:[]);assert.ok(ids.length>0);for(const i of ids){assert.ok(w.height[i]>=.23&&w.lakeDepth[i]<=.012);assert.equal(landformDetails(w,i).primary,'湖岛');}});

test('drainage ordering epsilon cannot raise summit elevation beyond the physical range',()=>{const w=new World(256,'验收-202',{climate:24,rain:.5});for(const h of w.height)assert.ok(h>=0&&h<=1);const loaded=World.load(w.serialize());assert.deepEqual(loaded.height,w.height);});
