import {updateRegions} from './regions.js';
import {World,FLOWS} from './world.js';
export const SCENARIOS=[['S01','山谷聚灵'],['S02','荒地藏灵'],['S03','灵泉养地'],['S04','一山两面'],['S05','源断地衰'],['S06','一树成地'],['S07','群草养地'],['S08','古林藏灵'],['S09','强植争灵'],['S10','树落草兴'],['S11','恶地育古树']];
// Only initial conditions and parameter interventions. No scenario ID reaches step().
export function scenario(id,variant='treatment'){
 const w=new World(32,'实验-'+id,{climate:21,rain:.55});
 for(let k=0;k<w.n*2;k++){w.type[k]=-1;w.count[k]=w.mass[k]=w.qi[k]=w.age[k]=w.life[k]=0;}w.cohortCount.fill(0);w.cohortBirth.fill(0);w.seedBank.fill(0);w.seedAge.fill(0);w.ancients={};w.terrainFeatures=[];w.river.fill(0);w.lakeDepth.fill(0);w.lakeIsland.fill(0);w.drainage.fill(-1);w.catchment.fill(0);w.events=[];w.edits=[];w.droppedEvents=0;w.lifeInput=w.lifeSpent=0;w.overrides={};
 for(let i=0;i<w.n;i++){w.height[i]=.4;w.rock[i]=.3;w.heat[i]=0;w.sun[i]=.75;w.baseTemp[i]=w.temp[i]=21;w.baseWater[i]=w.water[i]=.55;w.receive[i]=30;w.efficiency[i]=.8;w.production[i]=0;w.capacity[i]=800;w.ground[i]=w.air[i]=w.mineral[i]=w.soil[i]=w.detritus[i]=0;w.groundGatherRate[i]=w.gatherRate[i]=0;w.gatherLimit[i]=40;w.sourceMean[i]=w.throughputMean[i]=w.gatherMean[i]=0;w.conduct[i]=.5;w.outlet[i]=.02;w.mineralTime[i]=0;}
 const center=16*32+16,region=[];for(let y=14;y<=18;y++)for(let x=14;x<=18;x++)region.push(y*32+x);const seed=(i,t,n=20)=>{w.seedBank[i*8+t]=n;};
 const plant=(i,t,n=1,m=2,q=30,age=0,anc=false)=>{w.establish(i,t,n,m,false);const k=i*2+w.species[t].layer;w.qi[k]=q;w.age[k]=age;w.life[k]=n*(w.species[t].life-age);w.cohortCount.fill(0,k*8,k*8+8);w.addCohort(k,n,age);if(anc){w.removeCohorts(k,1);w.ancients[k]={age,mass:m,qi:q/n,life:w.species[t].life-age};}};
 w.rng=(5489+Number(id.slice(1))*15485863)>>>0;
 const control=variant==='control';
 if(id==='S01'){for(const i of region){w.ground[i]=200;w.production[i]=5;w.outlet[i]=control?0:.04;seed(i,2);}w.config.surfaceDiffusion=0;}
 if(id==='S02'){for(const i of region){w.rock[i]=control?.1:.9;w.ground[i]=500;w.production[i]=5;w.outlet[i]=.0001;w.baseTemp[i]=w.temp[i]=90;seed(i,2);}}
 if(id==='S03'||id==='S05'){w.groundGatherRate[center]=8;for(const i of region)if(i!==center)w.gatherRate[i]=.8;w.species[2].process=0;for(let x=4;x<=16;x++){const i=16*32+x;w.ground[i]=x<10?650:20;w.production[i]=x<10?8:0;w.outlet[i]=0;w.conduct[i]=1;}w.outlet[center]=.15;w.conduct[center]=id==='S05'?1:(control?0:1);plant(center,2,10,1,30);seed(center,2);if(id==='S05'){w.air[center]=6;w.ground[center]=20;for(let x=10;x<16;x++)w.ground[16*32+x]=500;}for(let i=0;i<w.n;i++)if(Math.floor(i/32)!==16)w.conduct[i]=0;}
 if(id==='S04'){for(const i of region){w.sun[i]=control?.3:.95;w.baseTemp[i]=w.temp[i]=control?17:23;w.baseWater[i]=w.water[i]=.45;seed(i,0);seed(i,1);}}
 if(id==='S06'){for(const i of region)if(i!==center)w.gatherRate[i]=.8;w.species[6].process=control?0:15;w.species[6].fertility=0;plant(center,6,1,4,150,120,true);for(const i of region)seed(i,2,50);}
 if(id==='S07'){for(const i of region){plant(i,2,control?2:45,1,control?5:112.5);w.species[2].process=.8;w.species[2].fertility=.1;}w.config.surfaceDiffusion=.05;}
 if(id==='S08'){for(const i of region){plant(i,6,1,3,230,110,true);w.species[6].process=0;w.species[6].release=control?.5:.005;w.species[6].fertility=0;w.detritus[i]=100;w.soil[i]=10;}w.config.decompose=control?.4:.005;}
 if(id==='S09'){w.species[6].growth=0;w.species[2].process=0;w.species[2].need=.5;w.species[2].absorb=.5;w.species[6].process=0;w.species[6].absorb=control?0:10;w.species[6].release=0;w.species[6].capacity=1000;w.species[6].fertility=0;plant(center,6,1,3,200,100,true);for(const i of region){w.air[i]=12;w.ground[i]=20;w.production[i]=.1;plant(i,2,8,1,10);}w.config.surfaceDiffusion=.5;}
 if(id==='S10'){for(const i of region)if(i!==center)w.gatherRate[i]=.8;plant(center,6,1,5,500,150,true);w.kill(center*2+1,'实验起点古树死亡');for(const i of region)seed(i,2,50);w.config.decompose=control?0:.25;}
 if(id==='S11'){for(const i of region){w.heat[i]=20;w.baseTemp[i]=w.temp[i]=38;w.baseWater[i]=w.water[i]=.5;w.production[i]=12;w.ground[i]=600;w.outlet[i]=.015;seed(i,2,50);}w.species[7].temp=38;w.species[7].water=.5;w.species[7].light=.75;w.species[7].fertility=0;w.species[7].growth=.15;w.species[7].shade=1;w.species[7].capacity=90;w.species[7].root=variant==='no-root'?0:5;w.species[7].absorb=0;w.species[7].process=0;w.species[2].temp=21;w.species[2].tol=19;w.config.seedLife=60;w.species[2].water=.6;w.species[2].light=.35;if(variant==='unfit')w.species[7].temp=-10;if(control)w.config.feedback=0;plant(center,7,1,2,10,70);}
 w.regions=undefined;w.ancientInfluences=[];w.year=w.steps=w.input=w.escaped=w.manual=w.errorAbsolute=0;w.initial=w.total();w.initialLife=w.lifeTotal();w.lifeInput=w.lifeSpent=0;w.before.fill(0);w.after.fill(0);for(const f of FLOWS)w.flows[f].fill(0);w.lastAudit={error:0,total:w.initial,input:0};w.refreshTotals();w.regions=updateRegions(w,true);if(id==='S05'&&control)w.edit({i:center,kind:'field',field:'conduct',value:0});return{world:w,center,region,id,variant};
}
export function observe(w,region,center){let ground=0,air=0,plantQi=0,detritus=0,mineral=0,grass=0,grassMass=0,trees=0,temp=0,water=0;const speciesCounts=Array(8).fill(0);for(const i of region){for(let l=0;l<2;l++)if(w.type[i*2+l]>=0)speciesCounts[w.type[i*2+l]]+=w.count[i*2+l];ground+=w.ground[i];air+=w.air[i];plantQi+=w.qi[i*2]+w.qi[i*2+1];detritus+=w.detritus[i]+w.soil[i];mineral+=w.mineral[i];grass+=w.count[i*2];grassMass+=w.mass[i*2];trees+=w.count[i*2+1];temp+=w.temp[i];water+=w.water[i];}return{year:w.year,speciesCounts,ground,air,plantQi,detritus,mineral,grass,grassMass,trees,temp:temp/region.length,water:water/region.length,centerTemp:w.temp[center],centerWater:w.water[center],centerGrass:w.count[center*2],centerTreeMass:w.mass[center*2+1],ancients:Object.keys(w.ancients).length,input:w.input,escaped:w.escaped,error:w.errorAbsolute};}
