import {ORIGIN,sceneGround,stairNear,SCENE_CAVES,LEDGES,sceneX,sceneY} from './mountain-scene.js';
import {mountainZone,routeHeight,MOUNTAIN_ROUTES,ROUTE_JUNCTIONS,junctionNear} from './mountain.js';
import {Terrain,Simulation,WIDTH,TOP,BOTTOM,TILE,LOCATIONS,MODES,CAVE_ENTRANCES,surface,buildings,isMineable,PLATFORMS} from './world.js';
import {spawn,move,relocate,overlaps} from './physics.js';
import {Renderer} from './render.js';
const $=id=>document.getElementById(id),canvas=$('world'),renderer=new Renderer(canvas),key='xiuxian-sideview-v3';
let saved=null;try{const v=JSON.parse(localStorage.getItem(key));if(v?.version===3&&Number.isFinite(v.player?.x)&&Number.isFinite(v.player?.y)&&MODES[v.player?.mode])saved=v;}catch{}
const terrain=new Terrain(saved?.edits),sim=new Simulation(saved?.simulation),player=Object.assign(spawn(),saved?.player),keys=new Set();
terrain.setRoute(player.route||'front');
if(mountainZone(player.x)&&player.terrainVersion!==4){player.x=ORIGIN+sceneX(3300);player.y=sceneY(-1240)-50;player.vy=0;player.cave=null;}player.terrainVersion=4;player.route='front';
let paused=false,last=performance.now(),monthClock=0,saveClock=0,hudClock=0,toastTime=8,nearby=null,nearbyCave=null,structures=buildings(sim),dialogBuilding=null,currency=saved?.currency??25;
$('mode').value=player.mode;
function notify(text){$('toast').textContent=text;toastTime=7;}
function save(){try{localStorage.setItem(key,JSON.stringify({version:3,player,simulation:sim,edits:[...terrain.edits],currency}));$('save-state').textContent='已保存';}catch{$('save-state').textContent='存储不可用';}}
function togglePanel(id){for(const other of ['atlas','observer','help'])if(other!==id)$(other).hidden=true;$(id).hidden=!$(id).hidden;if(id==='atlas'&&!$(id).hidden)drawMap();if(id==='observer')worldHUD();}
function updateStructures(){structures=buildings(sim);if(player.inside&&!structures.some(b=>b.id===player.inside&&!b.ruined))player.inside=null;}
function findNearby(){if(mountainZone(player.x)&&player.route!=='front')return null;let best=null,d=95;for(const b of structures){const distance=Math.hypot(b.x-player.x,(b.y-player.y)*.8);if(distance<d){d=distance;best=b;}}return best;}
function findNearbyCave(){if(mountainZone(player.x)&&player.route!=='front')return null;let best=null,d=105;for(const c of CAVE_ENTRANCES){const distance=Math.hypot(c.x-player.x,(c.y-player.y)*.8);if(distance<d){d=distance;best=c;}}return best;}
function worldHUD(){const owner=sim.factions[sim.mineOwner];$('world-state').innerHTML=[['矿场归属',owner.name],['剩余矿藏',sim.mineRemaining],['矿场库存',sim.mineStock.toFixed(0)],['城市库存',sim.cityStock.toFixed(0)],['矿石市价',sim.price+' 灵石'],['商路',sim.roadOpen?'畅通':'中断'],['流离人口',sim.refugees],...Object.values(sim.factions).map(f=>[f.name,f.status==='destroyed'?'解散 · 遗址保留':f.people+'人 / 经费'+Math.floor(f.wealth)])].map(([a,b])=>`<div class="stat"><span>${a}</span><b>${b}</b></div>`).join('');$('events').innerHTML=sim.history.slice(-30).reverse().map(e=>`<li>${e.year}年${e.month}月 · ${e.text}</li>`).join('')||'<li>尚无新事件；生产和运输每月运行。</li>';}
function openBuilding(){if(player.cave){player.cave=null;player.caveX=0;notify('离开洞窟，回到原来的山层。');return;}nearbyCave=findNearbyCave();if(nearbyCave){player.cave=nearbyCave.id;player.caveX=0;player.vx=player.vy=0;notify('进入'+nearbyCave.name+'；洞内画面覆盖外景。');return;}nearby=findNearby();if(!nearby){notify('靠近建筑或洞口后按 E。');return;}dialogBuilding=nearby;player.inside=nearby.id;player.vx=player.vy=0;$('interaction-title').textContent=nearby.name+(nearby.ruined?' · 遗址':'');const owner=sim.factions[nearby.owner];let text=nearby.ruined?'屋舍已经荒废，门梁和地基仍在。这里的主人离开了，建筑没有从世界上消失。':nearby.type==='shop'?'商人：矿石现价 '+sim.price+' 灵石。'+(sim.roadOpen?'商路畅通，货物按月送来。':'商路断了，库存正在减少。'):nearby.type==='ruin'?'石壁上的旧纹已经模糊。地面上的岁月过去了，这座旧殿仍留在矿层深处。':owner?owner.name+'现有'+owner.people+'人，经费'+Math.floor(owner.wealth)+'。'+(nearby.owner==='small'?'我们靠旧矿井与临河城的买卖维持山门。':'旅人可以在此歇脚。'):'风从旧门洞里吹过。';$('dialogue').textContent=text;$('actions').replaceChildren();
 const action=(label,fn,disabled=false)=>{const b=document.createElement('button');b.textContent=label;b.disabled=disabled;b.onclick=fn;$('actions').appendChild(b);};
 if(!nearby.ruined){action('歇息 · 恢复灵力',()=>{player.energy=MODES[player.mode].stamina;notify('灵力恢复。');closeBuilding();});if(nearby.type==='shop'){action('买1份矿石 · '+sim.price+'灵石',()=>{currency-=sim.price;sim.factions.city.wealth+=sim.price;sim.cityStock--;sim.ore++;sim.log('游历者购入1份矿石','player');closeBuilding();},currency<sim.price||sim.cityStock<1);action('卖1份矿石 · '+Math.max(1,sim.price-2)+'灵石',()=>{currency+=Math.max(1,sim.price-2);sim.factions.city.wealth-=Math.max(1,sim.price-2);sim.ore--;sim.cityStock++;sim.log('游历者售出1份矿石','player');closeBuilding();},sim.ore<1||sim.factions.city.wealth<Math.max(1,sim.price-2));}if(nearby.owner==='small')action('捐5份矿石 · 支持山门',()=>{if(sim.donate())notify('捐赠进入宗门经费；后续经营会使用这笔资源。');closeBuilding();},sim.ore<5);}
 $('interaction').showModal();save();}
function closeBuilding(){$('interaction').close();player.inside=null;dialogBuilding=null;canvas.focus();save();worldHUD();}
function dig(tx,ty){const x=(tx+.5)*TILE,y=(ty+.5)*TILE;if(Math.hypot(x-player.x,y-(player.y-18))>105){notify('只能处理身边的岩层。');return;}if(!isMineable(x,y)){notify('这里是稳定地基，不能开凿。矿井和已发现矿道才允许采掘。');return;}const t=terrain.get(tx,ty);if(![2,3].includes(t)){notify('这里没有可采围岩。');return;}terrain.set(tx,ty,0);if(t===3){notify(sim.extract()?'采得矿石 +1；矿场与个人开采共用同一矿藏。':'矿藏储备已耗尽。');}else notify('松动围岩已清理，矿道修改会保留。');save();}
function frame(now){const dt=Math.min(.033,(now-last)/1000);last=now;if(!paused&&!$('interaction').open){const input={left:keys.has('a')||keys.has('arrowleft'),right:keys.has('d')||keys.has('arrowright'),up:keys.has('w')||keys.has('arrowup'),down:keys.has('s')||keys.has('arrowdown'),jump:keys.has(' '),toggleFlight:keys.delete('flight')};if(player.cave){const direction=(input.right?1:0)-(input.left?1:0);if(direction)player.facing=direction;player.caveX=Math.max(-520,Math.min(520,(player.caveX||0)+direction*150*dt));}else move(player,terrain,input,dt);}
 if(!paused){monthClock+=dt;if(monthClock>=10){monthClock-=10;const before=sim.history.length;sim.tick();updateStructures();worldHUD();if(sim.history.length>before)notify('远方来报：'+sim.history.at(-1).text);}saveClock+=dt;if(saveClock>5){saveClock=0;save();}}
 renderer.draw(terrain,player,sim,structures,now/1000);hudClock+=dt;if(hudClock>.12){hudClock=0;hud();}toastTime-=dt;$('toast').style.opacity=toastTime>0?1:0;requestAnimationFrame(frame);}
function hud(){
 nearby=findNearby();nearbyCave=findNearbyCave();
 const rawDepth=player.y-surface(player.x),depth=Math.abs(rawDepth)<TILE?0:rawDepth;
 const loc=LOCATIONS.reduce((a,b)=>Math.hypot(player.x-a.x,(player.y-(a.y??surface(a.x)))*2)<Math.hypot(player.x-b.x,(player.y-(b.y??surface(b.x)))*2)?a:b);
 const foothill=player.y>-350&&((player.x>27000&&player.x<44500)||(player.x>94000&&player.x<135000));
 const activeCave=CAVE_ENTRANCES.find(v=>v.id===player.cave);
 $('place').textContent=activeCave?.name||(foothill?'山麓林径':Math.abs(loc.x-player.x)<2200?loc.name:depth>130?'地下矿层':player.y< -3000?'云海之上':'山野途中');
 $('altitude').textContent='距西界 '+(player.x/1000).toFixed(1)+' 千步 · 世界高程 '+Math.round(-player.y/10);
 $('stratum').textContent=mountainZone(player.x)?'谷地 · 林台 · 支峰 · 主峰，同域相连':player.y>1200?'地脉层 · 矿道与遗迹':player.y>650?'地下层 · 矿井与遗迹':player.y>-350?'第一层地基 · 林径与城镇':player.y>-1700?'山门地基 · 山林与城楼':player.y>-3600?'云下地基 · 支峰与院落':player.y>-6200?'云海地基 · 仙山诸峰':'天外层 · 浮空领域';
 $('date').textContent='大荒历 '+sim.year+'年 '+(sim.month+1)+'月';$('movement').textContent=MODES[player.mode].name+(player.flying?' · 飞行中':'');$('energy').max=MODES[player.mode].stamina;$('energy').value=player.energy;$('energy-value').textContent=Math.floor(player.energy);$('bag').textContent='矿石 '+sim.ore+' · 灵石 '+currency;$('streaming').textContent='附近 '+renderer.last.chunks+' 块 / 缓存 '+renderer.last.cached+' · 实体 '+renderer.last.entities;
 $('world-pulse').textContent='远方仍在演化 · '+sim.factions[sim.mineOwner].name+'掌矿 · 城中存矿 '+Math.floor(sim.cityStock)+' · '+(sim.roadOpen?'商路通行':'商路中断')+' · '+sim.factions.small.name+(sim.factions.small.status==='destroyed'?'已成遗址':'仍存');
 $('prompt').textContent=!player.cave&&mountainZone(player.x)&&stairNear(player)?'W / S · 沿贴山石阶升降 · V 远观 / 近看':player.cave?'A / D 探索洞内 · E 离开':nearbyCave?'E · 进入 '+nearbyCave.name:nearby?'E · '+(nearby.ruined?'查看遗址':nearby.type==='gate'?'查看山门':'进入')+' '+nearby.name:depth>100&&isMineable(player.x,player.y)?'W / S 爬梯 · K 开采矿道围岩':mountainZone(player.x)?'V 远观 / 近看 · A / D 行走 · W / S 石阶 · F 御器':player.mode!=='walk'?'F '+(player.flying?'收起御器 · W / S 升降':'御器起飞'):'';
 if(!$('atlas').hidden)drawMap();
}
function drawMap(){const c=$('route'),r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=220*d;const g=c.getContext('2d');g.scale(d,d);const width=r.width,toX=x=>x/WIDTH*width,toY=y=>16+(y-TOP)/(BOTTOM-TOP)*188;g.fillStyle='#152d37';g.fillRect(0,0,width,220);g.strokeStyle='#d9e0c21a';for(const y of [-6200,-3600,-1700,-350,650,1200]){g.beginPath();g.moveTo(0,toY(y));g.lineTo(width,toY(y));g.stroke();}g.fillStyle='#617966';g.beginPath();g.moveTo(0,220);for(let x=0;x<=WIDTH;x+=300)g.lineTo(toX(x),toY(mountainZone(x)?sceneGround(x):surface(x)));g.lineTo(width,220);g.fill();g.strokeStyle='#d7bd7a88';g.lineWidth=2;for(const p of PLATFORMS){if(mountainZone(p.x1))continue;g.beginPath();g.moveTo(toX(p.x1),toY(p.y));g.lineTo(toX(p.x2),toY(p.y));g.stroke();}for(const l of LEDGES){g.beginPath();l.points.forEach(([x,y],i)=>{if(i)g.lineTo(toX(ORIGIN+x),toY(y));else g.moveTo(toX(ORIGIN+x),toY(y));});g.stroke();}g.strokeStyle='#88b5bb';g.beginPath();g.moveTo(toX(40900),toY(surface(40900)));g.lineTo(toX(40900),toY(1550));g.lineTo(toX(44900),toY(1500));g.lineTo(toX(44900),toY(2900));g.stroke();g.font='10px serif';for(const l of LOCATIONS){const x=toX(l.x),y=toY(l.y??surface(l.x));g.fillStyle=l.kind==='sky'?'#e9d892':'#b8c9b6';g.fillRect(x-2,y-2,4,4);}g.fillStyle='#ffe0a0';g.beginPath();g.arc(toX(player.x),toY(player.y),4,0,Math.PI*2);g.fill();g.fillStyle='#a3bab2';g.fillText('天外',3,14);g.fillText('地表',3,toY(0));g.fillText('地脉',3,210);}
const TRAVEL_POINTS=[...LOCATIONS,...CAVE_ENTRANCES,{id:'study-valley',name:'层峦山域 · 谷地',x:ORIGIN+sceneX(3300),y:sceneGround(ORIGIN+sceneX(3300))},{id:'study-stair',name:'层峦山域 · 登山石阶',x:ORIGIN,y:380},{id:'study-court',name:'层峦山域 · 山腰院落',x:ORIGIN+sceneX(3300),y:sceneY(-1240)},{id:'study-peak',name:'层峦山域 · 云上主峰',x:ORIGIN+sceneX(4500),y:sceneY(-4200)}];
$('destinations').innerHTML=LOCATIONS.map(l=>`<span>${l.name}</span>`).join('');$('destination').innerHTML=TRAVEL_POINTS.map(l=>`<option value="${l.id}">${l.name}</option>`).join('');
$('travel').onclick=()=>{const l=TRAVEL_POINTS.find(l=>l.id===$('destination').value);player.cave=null;relocate(player,l.x,mountainZone(l.x)?(l.id.startsWith('study-')||SCENE_CAVES.some(c=>c.id===l.id)?l.y:sceneGround(l.x))-60:l.y!==undefined?l.y-60:undefined);terrain.setRoute(player.route);notify('观察定位：'+l.name+'。这不是正常旅行能力。');$('atlas').hidden=true;save();canvas.focus();};
$('mode').onchange=()=>{player.mode=$('mode').value;player.flying=false;player.energy=MODES[player.mode].stamina;notify(MODES[player.mode].name+'，'+(player.mode==='walk'?'空格跳跃。':'F 起飞，W / S 升降。'));canvas.focus();};
$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'继续':'暂停';};$('map-toggle').onclick=()=>togglePanel('atlas');$('observe-toggle').onclick=()=>togglePanel('observer');$('help-toggle').onclick=()=>togglePanel('help');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{$(b.dataset.close).hidden=true;canvas.focus();});$('leave').onclick=closeBuilding;$('interaction').addEventListener('cancel',()=>{player.inside=null;canvas.focus();});
$('retreat').onclick=()=>{sim.advance(20);updateStructures();worldHUD();notify('20年过去了。建筑、归属、人口与商品价格已按结算结果更新。');save();};$('road').onclick=()=>{sim.toggleRoad();worldHUD();notify('商路'+(sim.roadOpen?'恢复':'中断')+'，影响会在后续月份逐渐显现。');save();};
window.addEventListener('keydown',e=>{if(['INPUT','SELECT'].includes(document.activeElement.tagName)||$('interaction').open)return;const k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys.add(k);if(e.repeat)return;if(k==='v')renderer.overview=!renderer.overview;if(k==='f')keys.add('flight');if(k==='e')openBuilding();if(k==='m')togglePanel('atlas');if(k==='o')togglePanel('observer');if(k==='p')$('pause').click();if(k==='k')dig(Math.floor((player.x+player.facing*34)/TILE),Math.floor((player.y-14)/TILE));});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();save();});document.addEventListener('visibilitychange',()=>{keys.clear();save();});canvas.addEventListener('pointerdown',e=>{canvas.focus();const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/renderer.zoom+renderer.camera.x,y=(e.clientY-r.top)/renderer.zoom+renderer.camera.y;dig(Math.floor(x/TILE),Math.floor(y/TILE));});window.addEventListener('beforeunload',save);
updateStructures();worldHUD();requestAnimationFrame(frame);canvas.focus();
